[package]
name = "nightreign_ap"
version = "0.5.4"
edition = "2021"
description = "Archipelago runtime client for Elden Ring Nightreign"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
tungstenite = { version = "0.24", default-features = false, features = ["handshake", "native-tls"] }
