from typing import Dict, NamedTuple

from BaseClasses import ItemClassification

ITEM_ID_BASE = 839_100_000


class ItemSpec(NamedTuple):
    code: int
    classification: ItemClassification


item_table: Dict[str, ItemSpec] = {
    "Expedition Unlock - Tricephalos": ItemSpec(ITEM_ID_BASE + 1, ItemClassification.progression),
    "Expedition Unlock - Adel": ItemSpec(ITEM_ID_BASE + 2, ItemClassification.progression),
    "Expedition Unlock - Gnoster": ItemSpec(ITEM_ID_BASE + 3, ItemClassification.progression),
    "Expedition Unlock - Maris": ItemSpec(ITEM_ID_BASE + 4, ItemClassification.progression),
    "Expedition Unlock - Libra": ItemSpec(ITEM_ID_BASE + 5, ItemClassification.progression),
    "Expedition Unlock - Fulghor": ItemSpec(ITEM_ID_BASE + 6, ItemClassification.progression),
    "Expedition Unlock - Caligo": ItemSpec(ITEM_ID_BASE + 7, ItemClassification.progression),
    "Expedition Unlock - Heolstor": ItemSpec(ITEM_ID_BASE + 8, ItemClassification.progression),
    "Expedition Unlock - Harmonia": ItemSpec(ITEM_ID_BASE + 9, ItemClassification.progression),
    "Expedition Unlock - Straghess": ItemSpec(ITEM_ID_BASE + 10, ItemClassification.progression),
    "Everdark Unlock - Gladius": ItemSpec(ITEM_ID_BASE + 111, ItemClassification.progression),
    "Everdark Unlock - Adel": ItemSpec(ITEM_ID_BASE + 112, ItemClassification.progression),
    "Everdark Unlock - Gnoster": ItemSpec(ITEM_ID_BASE + 113, ItemClassification.progression),
    "Everdark Unlock - Maris": ItemSpec(ITEM_ID_BASE + 114, ItemClassification.progression),
    "Everdark Unlock - Libra": ItemSpec(ITEM_ID_BASE + 115, ItemClassification.progression),
    "Everdark Unlock - Fulghor": ItemSpec(ITEM_ID_BASE + 116, ItemClassification.progression),
    "Everdark Unlock - Caligo": ItemSpec(ITEM_ID_BASE + 117, ItemClassification.progression),
    "Everdark Unlock - Harmonia": ItemSpec(ITEM_ID_BASE + 118, ItemClassification.progression),
    "Nightfarer - Wylder": ItemSpec(ITEM_ID_BASE + 301, ItemClassification.useful),
    "Nightfarer - Duchess": ItemSpec(ITEM_ID_BASE + 302, ItemClassification.useful),
    "Nightfarer - Raider": ItemSpec(ITEM_ID_BASE + 303, ItemClassification.useful),
    "Nightfarer - Executor": ItemSpec(ITEM_ID_BASE + 304, ItemClassification.useful),
    "Nightfarer - Recluse": ItemSpec(ITEM_ID_BASE + 305, ItemClassification.useful),
    "Nightfarer - Ironeye": ItemSpec(ITEM_ID_BASE + 306, ItemClassification.useful),
    "Nightfarer - Guardian": ItemSpec(ITEM_ID_BASE + 307, ItemClassification.useful),
    "Nightfarer - Revenant": ItemSpec(ITEM_ID_BASE + 308, ItemClassification.useful),
    "Nightfarer - Scholar": ItemSpec(ITEM_ID_BASE + 309, ItemClassification.useful),
    "Nightfarer - Undertaker": ItemSpec(ITEM_ID_BASE + 310, ItemClassification.useful),
    "Shop - Polite Bow": ItemSpec(ITEM_ID_BASE + 501, ItemClassification.useful),
    "Shop - Strength": ItemSpec(ITEM_ID_BASE + 503, ItemClassification.useful),
    "Shop - Warm Welcome": ItemSpec(ITEM_ID_BASE + 504, ItemClassification.useful),
    "Shop - Delicate Burning Scene": ItemSpec(ITEM_ID_BASE + 505, ItemClassification.useful),
    "Shop - Heartening Cry": ItemSpec(ITEM_ID_BASE + 506, ItemClassification.useful),
    "Shop - Calm Down": ItemSpec(ITEM_ID_BASE + 507, ItemClassification.useful),
    "Shop - Besmirched Frame": ItemSpec(ITEM_ID_BASE + 510, ItemClassification.useful),
    "Shop - Wylder's Goblet": ItemSpec(ITEM_ID_BASE + 511, ItemClassification.useful),
    "Shop - Guardian's Goblet": ItemSpec(ITEM_ID_BASE + 512, ItemClassification.useful),
    "Shop - Ironeye's Goblet": ItemSpec(ITEM_ID_BASE + 513, ItemClassification.useful),
    "Shop - Duchess' Goblet": ItemSpec(ITEM_ID_BASE + 514, ItemClassification.useful),
    "Shop - Raider's Goblet": ItemSpec(ITEM_ID_BASE + 515, ItemClassification.useful),
    "Shop - Revenant's Goblet": ItemSpec(ITEM_ID_BASE + 516, ItemClassification.useful),
    "Shop - Recluse's Goblet": ItemSpec(ITEM_ID_BASE + 517, ItemClassification.useful),
    "Shop - Executor's Goblet": ItemSpec(ITEM_ID_BASE + 518, ItemClassification.useful),
    "Shop - Sacred Erdtree Grail": ItemSpec(ITEM_ID_BASE + 519, ItemClassification.useful),
    "Shop - Spirit Shelter Grail": ItemSpec(ITEM_ID_BASE + 520, ItemClassification.useful),
    "Shop - Giant's Cradle Grail": ItemSpec(ITEM_ID_BASE + 521, ItemClassification.useful),
    "Shop - Fancy Spin": ItemSpec(ITEM_ID_BASE + 522, ItemClassification.useful),
    "Shop - Crossed Legs": ItemSpec(ITEM_ID_BASE + 523, ItemClassification.useful),
    "Shop - Rest": ItemSpec(ITEM_ID_BASE + 524, ItemClassification.useful),
    "Shop - Sitting Sideways": ItemSpec(ITEM_ID_BASE + 525, ItemClassification.useful),
    "Shop - Fire Spur Me": ItemSpec(ITEM_ID_BASE + 526, ItemClassification.useful),
    "Shop - As You Wish": ItemSpec(ITEM_ID_BASE + 527, ItemClassification.useful),
    "Shop - Finger Snap": ItemSpec(ITEM_ID_BASE + 528, ItemClassification.useful),
    "Shop - Prayer": ItemSpec(ITEM_ID_BASE + 529, ItemClassification.useful),
    "Shop - Rapture": ItemSpec(ITEM_ID_BASE + 530, ItemClassification.useful),
    "Shop - Erudition": ItemSpec(ITEM_ID_BASE + 531, ItemClassification.useful),
    "Shop - Outer Order": ItemSpec(ITEM_ID_BASE + 532, ItemClassification.useful),
    "Shop - Curtsy": ItemSpec(ITEM_ID_BASE + 533, ItemClassification.useful),
    "Shop - Reverential Bow": ItemSpec(ITEM_ID_BASE + 534, ItemClassification.useful),
    "Shop - Dejection": ItemSpec(ITEM_ID_BASE + 535, ItemClassification.useful),
    "Shop - Extreme Repentance": ItemSpec(ITEM_ID_BASE + 536, ItemClassification.useful),
    "Shop - Patches' Crouch": ItemSpec(ITEM_ID_BASE + 537, ItemClassification.useful),
    "Shop - Dozing Cross-Legged": ItemSpec(ITEM_ID_BASE + 538, ItemClassification.useful),
    "Shop - Desperate Prayer": ItemSpec(ITEM_ID_BASE + 539, ItemClassification.useful),
    "Shop - Hoslow's Oath": ItemSpec(ITEM_ID_BASE + 540, ItemClassification.useful),
    "Shop - Inner Order": ItemSpec(ITEM_ID_BASE + 541, ItemClassification.useful),
    "Shop - What Do You Want?": ItemSpec(ITEM_ID_BASE + 542, ItemClassification.useful),
    "Shop - My Lord": ItemSpec(ITEM_ID_BASE + 543, ItemClassification.useful),
    "Shop - Grovel For Mercy": ItemSpec(ITEM_ID_BASE + 544, ItemClassification.useful),
    "Shop - Spread Out": ItemSpec(ITEM_ID_BASE + 545, ItemClassification.useful),
    "Shop - Balled Up": ItemSpec(ITEM_ID_BASE + 546, ItemClassification.useful),
    "Shop - Golden Order Totality": ItemSpec(ITEM_ID_BASE + 547, ItemClassification.useful),
    "Shop - Prattling Pate 'Hello"": ItemSpec(ITEM_ID_BASE + 548, ItemClassification.useful),
    "Shop - Prattling Pate 'Thank you"": ItemSpec(ITEM_ID_BASE + 549, ItemClassification.useful),
    "Shop - Prattling Pate 'Wonderful"": ItemSpec(ITEM_ID_BASE + 550, ItemClassification.useful),
    "Shop - Prattling Pate 'Please help"": ItemSpec(ITEM_ID_BASE + 551, ItemClassification.useful),
    "Shop - Prattling Pate 'My beloved"": ItemSpec(ITEM_ID_BASE + 552, ItemClassification.useful),
    "Shop - Prattling Pate 'Apologies"": ItemSpec(ITEM_ID_BASE + 553, ItemClassification.useful),
    "Shop - Prattling Pate 'Let's get to it"": ItemSpec(ITEM_ID_BASE + 554, ItemClassification.useful),
    "Shop - Prattling Pate 'You're beautiful"": ItemSpec(ITEM_ID_BASE + 555, ItemClassification.useful),
    "Shop - Scholar's Goblet": ItemSpec(ITEM_ID_BASE + 556, ItemClassification.useful),
    "Shop - Undertaker's Goblet": ItemSpec(ITEM_ID_BASE + 557, ItemClassification.useful),
    "Shop - Scadutree Grail": ItemSpec(ITEM_ID_BASE + 558, ItemClassification.useful),
    "Murk Bundle": ItemSpec(ITEM_ID_BASE + 100, ItemClassification.filler),
    "Victory": ItemSpec(ITEM_ID_BASE + 900, ItemClassification.progression),
}

ITEM_NAME_TO_ID = {name: spec.code for name, spec in item_table.items()}

# Base seven. Tricephalos is flag 189 in the regulation override.
# Heolstor is omitted from the pool unless heolstor_in_pool.
BASE_UNLOCKS = [
    "Expedition Unlock - Tricephalos",
    "Expedition Unlock - Adel",
    "Expedition Unlock - Gnoster",
    "Expedition Unlock - Maris",
    "Expedition Unlock - Libra",
    "Expedition Unlock - Fulghor",
    "Expedition Unlock - Caligo",
]

DLC_UNLOCKS = [
    "Expedition Unlock - Harmonia",
    "Expedition Unlock - Straghess",
]

EVERDARK_UNLOCKS = [
    "Everdark Unlock - Gladius",
    "Everdark Unlock - Adel",
    "Everdark Unlock - Gnoster",
    "Everdark Unlock - Maris",
    "Everdark Unlock - Libra",
    "Everdark Unlock - Fulghor",
    "Everdark Unlock - Caligo",
    "Everdark Unlock - Harmonia",
]

BASE_NIGHTFARERS = [
    "Nightfarer - Wylder",
    "Nightfarer - Duchess",
    "Nightfarer - Raider",
    "Nightfarer - Executor",
    "Nightfarer - Recluse",
    "Nightfarer - Ironeye",
    "Nightfarer - Guardian",
    "Nightfarer - Revenant",
]

DLC_NIGHTFARERS = [
    "Nightfarer - Scholar",
    "Nightfarer - Undertaker",
]

SHOP_ITEMS = [
    "Shop - Polite Bow",
    "Shop - Strength",
    "Shop - Warm Welcome",
    "Shop - Delicate Burning Scene",
    "Shop - Heartening Cry",
    "Shop - Calm Down",
    "Shop - Besmirched Frame",
    "Shop - Wylder's Goblet",
    "Shop - Guardian's Goblet",
    "Shop - Ironeye's Goblet",
    "Shop - Duchess' Goblet",
    "Shop - Raider's Goblet",
    "Shop - Revenant's Goblet",
    "Shop - Recluse's Goblet",
    "Shop - Executor's Goblet",
    "Shop - Sacred Erdtree Grail",
    "Shop - Spirit Shelter Grail",
    "Shop - Giant's Cradle Grail",
    "Shop - Fancy Spin",
    "Shop - Crossed Legs",
    "Shop - Rest",
    "Shop - Sitting Sideways",
    "Shop - Fire Spur Me",
    "Shop - As You Wish",
    "Shop - Finger Snap",
    "Shop - Prayer",
    "Shop - Rapture",
    "Shop - Erudition",
    "Shop - Outer Order",
    "Shop - Curtsy",
    "Shop - Reverential Bow",
    "Shop - Dejection",
    "Shop - Extreme Repentance",
    "Shop - Patches' Crouch",
    "Shop - Dozing Cross-Legged",
    "Shop - Desperate Prayer",
    "Shop - Hoslow's Oath",
    "Shop - Inner Order",
    "Shop - What Do You Want?",
    "Shop - My Lord",
    "Shop - Grovel For Mercy",
    "Shop - Spread Out",
    "Shop - Balled Up",
    "Shop - Golden Order Totality",
    "Shop - Prattling Pate 'Hello"",
    "Shop - Prattling Pate 'Thank you"",
    "Shop - Prattling Pate 'Wonderful"",
    "Shop - Prattling Pate 'Please help"",
    "Shop - Prattling Pate 'My beloved"",
    "Shop - Prattling Pate 'Apologies"",
    "Shop - Prattling Pate 'Let's get to it"",
    "Shop - Prattling Pate 'You're beautiful"",
    "Shop - Scholar's Goblet",
    "Shop - Undertaker's Goblet",
    "Shop - Scadutree Grail",
]
