from typing import Dict, NamedTuple

from BaseClasses import ItemClassification

ITEM_ID_BASE = 839_100_000


class ItemSpec(NamedTuple):
    code: int
    classification: ItemClassification


item_table: Dict[str, ItemSpec] = {
    "Expedition Unlock - Tricephalos": ItemSpec(ITEM_ID_BASE + 1, ItemClassification.progression),
    "Expedition Unlock - Adel": ItemSpec(ITEM_ID_BASE + 2, ItemClassification.progression),
    "Expedition Unlock - Gnoster": ItemSpec(ITEM_ID_BASE + 3, ItemClassification.progression),
    "Expedition Unlock - Maris": ItemSpec(ITEM_ID_BASE + 4, ItemClassification.progression),
    "Expedition Unlock - Libra": ItemSpec(ITEM_ID_BASE + 5, ItemClassification.progression),
    "Expedition Unlock - Fulghor": ItemSpec(ITEM_ID_BASE + 6, ItemClassification.progression),
    "Expedition Unlock - Caligo": ItemSpec(ITEM_ID_BASE + 7, ItemClassification.progression),
    "Expedition Unlock - Heolstor": ItemSpec(ITEM_ID_BASE + 8, ItemClassification.progression),
    "Expedition Unlock - Harmonia": ItemSpec(ITEM_ID_BASE + 9, ItemClassification.progression),
    "Expedition Unlock - Straghess": ItemSpec(ITEM_ID_BASE + 10, ItemClassification.progression),
    "Expedition Unlock - Deep of Night": ItemSpec(ITEM_ID_BASE + 11, ItemClassification.useful),
    "Everdark Unlock - Gladius": ItemSpec(ITEM_ID_BASE + 111, ItemClassification.progression),
    "Everdark Unlock - Adel": ItemSpec(ITEM_ID_BASE + 112, ItemClassification.progression),
    "Everdark Unlock - Gnoster": ItemSpec(ITEM_ID_BASE + 113, ItemClassification.progression),
    "Everdark Unlock - Maris": ItemSpec(ITEM_ID_BASE + 114, ItemClassification.progression),
    "Everdark Unlock - Libra": ItemSpec(ITEM_ID_BASE + 115, ItemClassification.progression),
    "Everdark Unlock - Fulghor": ItemSpec(ITEM_ID_BASE + 116, ItemClassification.progression),
    "Everdark Unlock - Caligo": ItemSpec(ITEM_ID_BASE + 117, ItemClassification.progression),
    "Everdark Unlock - Harmonia": ItemSpec(ITEM_ID_BASE + 118, ItemClassification.progression),
    "Nightfarer - Wylder": ItemSpec(ITEM_ID_BASE + 301, ItemClassification.useful),
    "Nightfarer - Duchess": ItemSpec(ITEM_ID_BASE + 302, ItemClassification.useful),
    "Nightfarer - Raider": ItemSpec(ITEM_ID_BASE + 303, ItemClassification.useful),
    "Nightfarer - Executor": ItemSpec(ITEM_ID_BASE + 304, ItemClassification.useful),
    "Nightfarer - Recluse": ItemSpec(ITEM_ID_BASE + 305, ItemClassification.useful),
    "Nightfarer - Ironeye": ItemSpec(ITEM_ID_BASE + 306, ItemClassification.useful),
    "Nightfarer - Guardian": ItemSpec(ITEM_ID_BASE + 307, ItemClassification.useful),
    "Nightfarer - Revenant": ItemSpec(ITEM_ID_BASE + 308, ItemClassification.useful),
    "Nightfarer - Scholar": ItemSpec(ITEM_ID_BASE + 309, ItemClassification.useful),
    "Nightfarer - Undertaker": ItemSpec(ITEM_ID_BASE + 310, ItemClassification.useful),
    "Murk Purse": ItemSpec(ITEM_ID_BASE + 105, ItemClassification.filler),
    "Murk Bundle": ItemSpec(ITEM_ID_BASE + 101, ItemClassification.filler),
    "Murk Coffer": ItemSpec(ITEM_ID_BASE + 102, ItemClassification.filler),
    "Murk Chest": ItemSpec(ITEM_ID_BASE + 103, ItemClassification.filler),
    "Murk Hoard": ItemSpec(ITEM_ID_BASE + 104, ItemClassification.filler),
    "Shop - Delicate Burning Scene": ItemSpec(ITEM_ID_BASE + 600, ItemClassification.progression),
    "Shop - Delicate Drizzly Scene": ItemSpec(ITEM_ID_BASE + 601, ItemClassification.progression),
    "Shop - Delicate Luminous Scene 1": ItemSpec(ITEM_ID_BASE + 602, ItemClassification.progression),
    "Shop - Delicate Tranquil Scene": ItemSpec(ITEM_ID_BASE + 603, ItemClassification.progression),
    "Shop - Polished Burning Scene 1": ItemSpec(ITEM_ID_BASE + 604, ItemClassification.progression),
    "Shop - Delicate Luminous Scene 2": ItemSpec(ITEM_ID_BASE + 605, ItemClassification.progression),
    "Shop - Polished Tranquil Scene 1": ItemSpec(ITEM_ID_BASE + 606, ItemClassification.progression),
    "Shop - Polished Drizzly Scene 1": ItemSpec(ITEM_ID_BASE + 607, ItemClassification.progression),
    "Shop - Polished Burning Scene 2": ItemSpec(ITEM_ID_BASE + 608, ItemClassification.progression),
    "Shop - Polished Tranquil Scene 2": ItemSpec(ITEM_ID_BASE + 609, ItemClassification.progression),
    "Shop - Polished Tranquil Scene 3": ItemSpec(ITEM_ID_BASE + 610, ItemClassification.progression),
    "Shop - Polished Burning Scene 3": ItemSpec(ITEM_ID_BASE + 611, ItemClassification.progression),
    "Shop - Polished Burning Scene 4": ItemSpec(ITEM_ID_BASE + 612, ItemClassification.progression),
    "Shop - Polished Tranquil Scene 4": ItemSpec(ITEM_ID_BASE + 613, ItemClassification.progression),
    "Shop - Polished Luminous Scene 1": ItemSpec(ITEM_ID_BASE + 614, ItemClassification.progression),
    "Shop - Polished Luminous Scene 2": ItemSpec(ITEM_ID_BASE + 615, ItemClassification.progression),
    "Shop - Polished Drizzly Scene 2": ItemSpec(ITEM_ID_BASE + 616, ItemClassification.progression),
    "Shop - Polished Drizzly Scene 3": ItemSpec(ITEM_ID_BASE + 617, ItemClassification.progression),
    "Shop - Grand Burning Scene 1": ItemSpec(ITEM_ID_BASE + 618, ItemClassification.progression),
    "Shop - Grand Drizzly Scene 1": ItemSpec(ITEM_ID_BASE + 619, ItemClassification.progression),
    "Shop - Grand Tranquil Scene 1": ItemSpec(ITEM_ID_BASE + 620, ItemClassification.progression),
    "Shop - Grand Tranquil Scene 2": ItemSpec(ITEM_ID_BASE + 621, ItemClassification.progression),
    "Shop - Grand Luminous Scene": ItemSpec(ITEM_ID_BASE + 622, ItemClassification.progression),
    "Shop - Grand Drizzly Scene 2": ItemSpec(ITEM_ID_BASE + 623, ItemClassification.progression),
    "Shop - Grand Drizzly Scene 3": ItemSpec(ITEM_ID_BASE + 624, ItemClassification.progression),
    "Shop - Grand Burning Scene 2": ItemSpec(ITEM_ID_BASE + 625, ItemClassification.progression),
    "Shop - Grand Burning Scene 3": ItemSpec(ITEM_ID_BASE + 626, ItemClassification.progression),
    "Shop - Grand Tranquil Scene 3": ItemSpec(ITEM_ID_BASE + 627, ItemClassification.progression),
    "Shop - Besmirched Frame": ItemSpec(ITEM_ID_BASE + 628, ItemClassification.progression),
    "Shop - Wylder's Goblet": ItemSpec(ITEM_ID_BASE + 629, ItemClassification.progression),
    "Shop - Guardian's Goblet": ItemSpec(ITEM_ID_BASE + 630, ItemClassification.progression),
    "Shop - Ironeye's Goblet": ItemSpec(ITEM_ID_BASE + 631, ItemClassification.progression),
    "Shop - Duchess' Goblet": ItemSpec(ITEM_ID_BASE + 632, ItemClassification.progression),
    "Shop - Raider's Goblet": ItemSpec(ITEM_ID_BASE + 633, ItemClassification.progression),
    "Shop - Revenant's Goblet": ItemSpec(ITEM_ID_BASE + 634, ItemClassification.progression),
    "Shop - Recluse's Goblet": ItemSpec(ITEM_ID_BASE + 635, ItemClassification.progression),
    "Shop - Executor's Goblet": ItemSpec(ITEM_ID_BASE + 636, ItemClassification.progression),
    "Shop - Sacred Erdtree Grail": ItemSpec(ITEM_ID_BASE + 637, ItemClassification.progression),
    "Shop - Spirit Shelter Grail": ItemSpec(ITEM_ID_BASE + 638, ItemClassification.progression),
    "Shop - Giant's Cradle Grail": ItemSpec(ITEM_ID_BASE + 639, ItemClassification.progression),
    "Shop - Polite Bow": ItemSpec(ITEM_ID_BASE + 640, ItemClassification.progression),
    "Shop - Strength": ItemSpec(ITEM_ID_BASE + 641, ItemClassification.progression),
    "Shop - Warm Welcome": ItemSpec(ITEM_ID_BASE + 642, ItemClassification.progression),
    "Shop - Fancy Spin": ItemSpec(ITEM_ID_BASE + 643, ItemClassification.progression),
    "Shop - Crossed Legs": ItemSpec(ITEM_ID_BASE + 644, ItemClassification.progression),
    "Shop - Rest": ItemSpec(ITEM_ID_BASE + 645, ItemClassification.progression),
    "Shop - Sitting Sideways": ItemSpec(ITEM_ID_BASE + 646, ItemClassification.progression),
    "Shop - Fire Spur Me": ItemSpec(ITEM_ID_BASE + 647, ItemClassification.progression),
    "Shop - As You Wish": ItemSpec(ITEM_ID_BASE + 648, ItemClassification.progression),
    "Shop - Heartening Cry": ItemSpec(ITEM_ID_BASE + 649, ItemClassification.progression),
    "Shop - Calm Down": ItemSpec(ITEM_ID_BASE + 650, ItemClassification.progression),
    "Shop - Finger Snap": ItemSpec(ITEM_ID_BASE + 651, ItemClassification.progression),
    "Shop - Prayer": ItemSpec(ITEM_ID_BASE + 652, ItemClassification.progression),
    "Shop - Rapture": ItemSpec(ITEM_ID_BASE + 653, ItemClassification.progression),
    "Shop - Erudition": ItemSpec(ITEM_ID_BASE + 654, ItemClassification.progression),
    "Shop - Outer Order": ItemSpec(ITEM_ID_BASE + 655, ItemClassification.progression),
    "Shop - Curtsy": ItemSpec(ITEM_ID_BASE + 656, ItemClassification.progression),
    "Shop - Reverential Bow": ItemSpec(ITEM_ID_BASE + 657, ItemClassification.progression),
    "Shop - Dejection": ItemSpec(ITEM_ID_BASE + 658, ItemClassification.progression),
    "Shop - Extreme Repentance": ItemSpec(ITEM_ID_BASE + 659, ItemClassification.progression),
    "Shop - Patches' Crouch": ItemSpec(ITEM_ID_BASE + 660, ItemClassification.progression),
    "Shop - Dozing Cross-Legged": ItemSpec(ITEM_ID_BASE + 661, ItemClassification.progression),
    "Shop - Desperate Prayer": ItemSpec(ITEM_ID_BASE + 662, ItemClassification.progression),
    "Shop - Hoslow's Oath": ItemSpec(ITEM_ID_BASE + 663, ItemClassification.progression),
    "Shop - Inner Order": ItemSpec(ITEM_ID_BASE + 664, ItemClassification.progression),
    "Shop - What Do You Want?": ItemSpec(ITEM_ID_BASE + 665, ItemClassification.progression),
    "Shop - My Lord": ItemSpec(ITEM_ID_BASE + 666, ItemClassification.progression),
    "Shop - Grovel For Mercy": ItemSpec(ITEM_ID_BASE + 667, ItemClassification.progression),
    "Shop - Spread Out": ItemSpec(ITEM_ID_BASE + 668, ItemClassification.progression),
    "Shop - Balled Up": ItemSpec(ITEM_ID_BASE + 669, ItemClassification.progression),
    "Shop - Golden Order Totality": ItemSpec(ITEM_ID_BASE + 670, ItemClassification.progression),
    "Shop - Prattling Pate Hello": ItemSpec(ITEM_ID_BASE + 671, ItemClassification.progression),
    "Shop - Prattling Pate Thank you": ItemSpec(ITEM_ID_BASE + 672, ItemClassification.progression),
    "Shop - Prattling Pate Wonderful": ItemSpec(ITEM_ID_BASE + 673, ItemClassification.progression),
    "Shop - Prattling Pate Please help": ItemSpec(ITEM_ID_BASE + 674, ItemClassification.progression),
    "Shop - Prattling Pate My beloved": ItemSpec(ITEM_ID_BASE + 675, ItemClassification.progression),
    "Shop - Prattling Pate Apologies": ItemSpec(ITEM_ID_BASE + 676, ItemClassification.progression),
    "Shop - Prattling Pate Let's get to it": ItemSpec(ITEM_ID_BASE + 677, ItemClassification.progression),
    "Shop - Prattling Pate You're beautiful": ItemSpec(ITEM_ID_BASE + 678, ItemClassification.progression),
    "Shop - Scholar's Goblet": ItemSpec(ITEM_ID_BASE + 679, ItemClassification.progression),
    "Shop - Undertaker's Goblet": ItemSpec(ITEM_ID_BASE + 680, ItemClassification.progression),
    "Shop - Scadutree Grail": ItemSpec(ITEM_ID_BASE + 681, ItemClassification.progression),
    "Shop - Grand Burning Scene 4": ItemSpec(ITEM_ID_BASE + 682, ItemClassification.progression),
    "Shop - Grand Tranquil Scene 4": ItemSpec(ITEM_ID_BASE + 683, ItemClassification.progression),
    "Victory": ItemSpec(ITEM_ID_BASE + 900, ItemClassification.progression),
}

ITEM_NAME_TO_ID = {name: spec.code for name, spec in item_table.items()}

# Base seven. Tricephalos is flag 189 in the regulation override.
# Heolstor is omitted from the pool unless heolstor_in_pool.
BASE_UNLOCKS = [
    "Expedition Unlock - Tricephalos",
    "Expedition Unlock - Adel",
    "Expedition Unlock - Gnoster",
    "Expedition Unlock - Maris",
    "Expedition Unlock - Libra",
    "Expedition Unlock - Fulghor",
    "Expedition Unlock - Caligo",
]

DLC_UNLOCKS = [
    "Expedition Unlock - Harmonia",
    "Expedition Unlock - Straghess",
]

# Flag 130. Always in the pool, never the starting expedition.
DEPTH_UNLOCKS = [
    "Expedition Unlock - Deep of Night",
]

EVERDARK_UNLOCKS = [
    "Everdark Unlock - Gladius",
    "Everdark Unlock - Adel",
    "Everdark Unlock - Gnoster",
    "Everdark Unlock - Maris",
    "Everdark Unlock - Libra",
    "Everdark Unlock - Fulghor",
    "Everdark Unlock - Caligo",
    "Everdark Unlock - Harmonia",
]

BASE_NIGHTFARERS = [
    "Nightfarer - Wylder",
    "Nightfarer - Duchess",
    "Nightfarer - Raider",
    "Nightfarer - Executor",
    "Nightfarer - Recluse",
    "Nightfarer - Ironeye",
    "Nightfarer - Guardian",
    "Nightfarer - Revenant",
]

DLC_NIGHTFARERS = [
    "Nightfarer - Scholar",
    "Nightfarer - Undertaker",
]

SHOP_ITEMS = [
    "Shop - Delicate Burning Scene",
    "Shop - Delicate Drizzly Scene",
    "Shop - Delicate Luminous Scene 1",
    "Shop - Delicate Tranquil Scene",
    "Shop - Polished Burning Scene 1",
    "Shop - Delicate Luminous Scene 2",
    "Shop - Polished Tranquil Scene 1",
    "Shop - Polished Drizzly Scene 1",
    "Shop - Polished Burning Scene 2",
    "Shop - Polished Tranquil Scene 2",
    "Shop - Polished Tranquil Scene 3",
    "Shop - Polished Burning Scene 3",
    "Shop - Polished Burning Scene 4",
    "Shop - Polished Tranquil Scene 4",
    "Shop - Polished Luminous Scene 1",
    "Shop - Polished Luminous Scene 2",
    "Shop - Polished Drizzly Scene 2",
    "Shop - Polished Drizzly Scene 3",
    "Shop - Grand Burning Scene 1",
    "Shop - Grand Drizzly Scene 1",
    "Shop - Grand Tranquil Scene 1",
    "Shop - Grand Tranquil Scene 2",
    "Shop - Grand Luminous Scene",
    "Shop - Grand Drizzly Scene 2",
    "Shop - Grand Drizzly Scene 3",
    "Shop - Grand Burning Scene 2",
    "Shop - Grand Burning Scene 3",
    "Shop - Grand Tranquil Scene 3",
    "Shop - Besmirched Frame",
    "Shop - Wylder's Goblet",
    "Shop - Guardian's Goblet",
    "Shop - Ironeye's Goblet",
    "Shop - Duchess' Goblet",
    "Shop - Raider's Goblet",
    "Shop - Revenant's Goblet",
    "Shop - Recluse's Goblet",
    "Shop - Executor's Goblet",
    "Shop - Sacred Erdtree Grail",
    "Shop - Spirit Shelter Grail",
    "Shop - Giant's Cradle Grail",
    "Shop - Polite Bow",
    "Shop - Strength",
    "Shop - Warm Welcome",
    "Shop - Fancy Spin",
    "Shop - Crossed Legs",
    "Shop - Rest",
    "Shop - Sitting Sideways",
    "Shop - Fire Spur Me",
    "Shop - As You Wish",
    "Shop - Heartening Cry",
    "Shop - Calm Down",
    "Shop - Finger Snap",
    "Shop - Prayer",
    "Shop - Rapture",
    "Shop - Erudition",
    "Shop - Outer Order",
    "Shop - Curtsy",
    "Shop - Reverential Bow",
    "Shop - Dejection",
    "Shop - Extreme Repentance",
    "Shop - Patches' Crouch",
    "Shop - Dozing Cross-Legged",
    "Shop - Desperate Prayer",
    "Shop - Hoslow's Oath",
    "Shop - Inner Order",
    "Shop - What Do You Want?",
    "Shop - My Lord",
    "Shop - Grovel For Mercy",
    "Shop - Spread Out",
    "Shop - Balled Up",
    "Shop - Golden Order Totality",
    "Shop - Prattling Pate Hello",
    "Shop - Prattling Pate Thank you",
    "Shop - Prattling Pate Wonderful",
    "Shop - Prattling Pate Please help",
    "Shop - Prattling Pate My beloved",
    "Shop - Prattling Pate Apologies",
    "Shop - Prattling Pate Let's get to it",
    "Shop - Prattling Pate You're beautiful",
    "Shop - Scholar's Goblet",
    "Shop - Undertaker's Goblet",
    "Shop - Scadutree Grail",
    "Shop - Grand Burning Scene 4",
    "Shop - Grand Tranquil Scene 4",
]
