from typing import Dict, List, Tuple

LOCATION_ID_BASE = 839_000_000

# Shop ids match flags.toml and CSFD4VirtualMemoryFlag::GetFlag on 1.3.3.0.
LOCATION_NAME_TO_ID: Dict[str, int] = {
    "Nightlord - Gladius": LOCATION_ID_BASE + 1,
    "Nightlord - Adel": LOCATION_ID_BASE + 2,
    "Nightlord - Gnoster": LOCATION_ID_BASE + 3,
    "Nightlord - Maris": LOCATION_ID_BASE + 4,
    "Nightlord - Libra": LOCATION_ID_BASE + 5,
    "Nightlord - Fulghor": LOCATION_ID_BASE + 6,
    "Nightlord - Caligo": LOCATION_ID_BASE + 7,
    "Nightlord - Heolstor": LOCATION_ID_BASE + 8,
    "Nightlord - Harmonia": LOCATION_ID_BASE + 9,
    "Nightlord - Straghess": LOCATION_ID_BASE + 10,
    "Board unlock after first Nightlord": LOCATION_ID_BASE + 100,
    "Everdark - Gladius": LOCATION_ID_BASE + 101,
    "Everdark - Adel": LOCATION_ID_BASE + 102,
    "Everdark - Gnoster": LOCATION_ID_BASE + 103,
    "Everdark - Maris": LOCATION_ID_BASE + 104,
    "Everdark - Libra": LOCATION_ID_BASE + 105,
    "Everdark - Fulghor": LOCATION_ID_BASE + 106,
    "Everdark - Caligo": LOCATION_ID_BASE + 107,
    "Everdark - Harmonia": LOCATION_ID_BASE + 108,
    "Goal - Nightlord Count": LOCATION_ID_BASE + 200,
    'Shop - Prattling Pate Hello': LOCATION_ID_BASE + + 548,
    'Shop - Prattling Pate Thank you': LOCATION_ID_BASE + + 549,
    'Shop - Prattling Pate Wonderful': LOCATION_ID_BASE + + 550,
    'Shop - Prattling Pate Please help': LOCATION_ID_BASE + + 551,
    'Shop - Prattling Pate My beloved': LOCATION_ID_BASE + + 552,
    'Shop - Prattling Pate Apologies': LOCATION_ID_BASE + + 553,
    'Shop - Prattling Pate Lets get to it': LOCATION_ID_BASE + + 554,
    'Shop - Prattling Pate Youre beautiful': LOCATION_ID_BASE + + 555,
    "Shop - Delicate Burning Scene (10000)": LOCATION_ID_BASE + 600,
    "Shop - Delicate Drizzly Scene (10001)": LOCATION_ID_BASE + 601,
    "Shop - Delicate Luminous Scene (10002)": LOCATION_ID_BASE + 602,
    "Shop - Delicate Tranquil Scene (10003)": LOCATION_ID_BASE + 603,
    "Shop - Polished Burning Scene (10004)": LOCATION_ID_BASE + 604,
    "Shop - Delicate Luminous Scene (10005)": LOCATION_ID_BASE + 605,
    "Shop - Polished Tranquil Scene (10010)": LOCATION_ID_BASE + 606,
    "Shop - Polished Drizzly Scene (10011)": LOCATION_ID_BASE + 607,
    "Shop - Polished Burning Scene (10012)": LOCATION_ID_BASE + 608,
    "Shop - Polished Tranquil Scene (10013)": LOCATION_ID_BASE + 609,
    "Shop - Polished Tranquil Scene (10014)": LOCATION_ID_BASE + 610,
    "Shop - Polished Burning Scene (10015)": LOCATION_ID_BASE + 611,
    "Shop - Polished Burning Scene (10020)": LOCATION_ID_BASE + 612,
    "Shop - Polished Tranquil Scene (10021)": LOCATION_ID_BASE + 613,
    "Shop - Polished Luminous Scene (10022)": LOCATION_ID_BASE + 614,
    "Shop - Polished Luminous Scene (10023)": LOCATION_ID_BASE + 615,
    "Shop - Polished Drizzly Scene (10024)": LOCATION_ID_BASE + 616,
    "Shop - Polished Drizzly Scene (10025)": LOCATION_ID_BASE + 617,
    "Shop - Grand Burning Scene (10030)": LOCATION_ID_BASE + 618,
    "Shop - Grand Drizzly Scene (10031)": LOCATION_ID_BASE + 619,
    "Shop - Grand Tranquil Scene (10032)": LOCATION_ID_BASE + 620,
    "Shop - Grand Tranquil Scene (10033)": LOCATION_ID_BASE + 621,
    "Shop - Grand Luminous Scene (10034)": LOCATION_ID_BASE + 622,
    "Shop - Grand Drizzly Scene (10035)": LOCATION_ID_BASE + 623,
    "Shop - Grand Drizzly Scene (10036)": LOCATION_ID_BASE + 624,
    "Shop - Grand Burning Scene (10037)": LOCATION_ID_BASE + 625,
    "Shop - Grand Burning Scene (10040)": LOCATION_ID_BASE + 626,
    "Shop - Grand Tranquil Scene (10041)": LOCATION_ID_BASE + 627,
    "Shop - Besmirched Frame (10100)": LOCATION_ID_BASE + 628,
    "Shop - Wylder's Goblet (10121)": LOCATION_ID_BASE + 629,
    "Shop - Guardian's Goblet (10123)": LOCATION_ID_BASE + 630,
    "Shop - Ironeye's Goblet (10125)": LOCATION_ID_BASE + 631,
    "Shop - Duchess' Goblet (10127)": LOCATION_ID_BASE + 632,
    "Shop - Raider's Goblet (10129)": LOCATION_ID_BASE + 633,
    "Shop - Revenant's Goblet (10131)": LOCATION_ID_BASE + 634,
    "Shop - Recluse's Goblet (10133)": LOCATION_ID_BASE + 635,
    "Shop - Executor's Goblet (10135)": LOCATION_ID_BASE + 636,
    "Shop - Sacred Erdtree Grail (10140)": LOCATION_ID_BASE + 637,
    "Shop - Spirit Shelter Grail (10141)": LOCATION_ID_BASE + 638,
    "Shop - Giant's Cradle Grail (10142)": LOCATION_ID_BASE + 639,
    "Shop - Polite Bow (10150)": LOCATION_ID_BASE + 640,
    "Shop - Strength (10151)": LOCATION_ID_BASE + 641,
    "Shop - Warm Welcome (10152)": LOCATION_ID_BASE + 642,
    "Shop - Fancy Spin (10153)": LOCATION_ID_BASE + 643,
    "Shop - Crossed Legs (10154)": LOCATION_ID_BASE + 644,
    "Shop - Rest (10155)": LOCATION_ID_BASE + 645,
    "Shop - Sitting Sideways (10156)": LOCATION_ID_BASE + 646,
    "Shop - Fire Spur Me (10157)": LOCATION_ID_BASE + 647,
    "Shop - As You Wish (10160)": LOCATION_ID_BASE + 648,
    "Shop - Heartening Cry (10161)": LOCATION_ID_BASE + 649,
    "Shop - Calm Down (10162)": LOCATION_ID_BASE + 650,
    "Shop - Finger Snap (10163)": LOCATION_ID_BASE + 651,
    "Shop - Prayer (10164)": LOCATION_ID_BASE + 652,
    "Shop - Rapture (10165)": LOCATION_ID_BASE + 653,
    "Shop - Erudition (10166)": LOCATION_ID_BASE + 654,
    "Shop - Outer Order (10167)": LOCATION_ID_BASE + 655,
    "Shop - Curtsy (10170)": LOCATION_ID_BASE + 656,
    "Shop - Reverential Bow (10171)": LOCATION_ID_BASE + 657,
    "Shop - Dejection (10172)": LOCATION_ID_BASE + 658,
    "Shop - Extreme Repentance (10173)": LOCATION_ID_BASE + 659,
    "Shop - Patches' Crouch (10174)": LOCATION_ID_BASE + 660,
    "Shop - Dozing Cross-Legged (10175)": LOCATION_ID_BASE + 661,
    "Shop - Desperate Prayer (10176)": LOCATION_ID_BASE + 662,
    "Shop - Hoslow's Oath (10177)": LOCATION_ID_BASE + 663,
    "Shop - Inner Order (10178)": LOCATION_ID_BASE + 664,
    "Shop - What Do You Want? (10180)": LOCATION_ID_BASE + 665,
    "Shop - My Lord (10181)": LOCATION_ID_BASE + 666,
    "Shop - Grovel For Mercy (10182)": LOCATION_ID_BASE + 667,
    "Shop - Spread Out (10183)": LOCATION_ID_BASE + 668,
    "Shop - Balled Up (10184)": LOCATION_ID_BASE + 669,
    "Shop - Golden Order Totality (10185)": LOCATION_ID_BASE + 670,
    "Shop - Prattling Pate Hello (10190)": LOCATION_ID_BASE + 671,
    "Shop - Prattling Pate Thank you (10191)": LOCATION_ID_BASE + 672,
    "Shop - Prattling Pate Wonderful (10192)": LOCATION_ID_BASE + 673,
    "Shop - Prattling Pate Please help (10193)": LOCATION_ID_BASE + 674,
    "Shop - Prattling Pate My beloved (10194)": LOCATION_ID_BASE + 675,
    "Shop - Prattling Pate Apologies (10195)": LOCATION_ID_BASE + 676,
    "Shop - Prattling Pate Let's get to it (10196)": LOCATION_ID_BASE + 677,
    "Shop - Prattling Pate You're beautiful (10197)": LOCATION_ID_BASE + 678,
    "Shop - Scholar's Goblet (10281)": LOCATION_ID_BASE + 679,
    "Shop - Undertaker's Goblet (10291)": LOCATION_ID_BASE + 680,
    "Shop - Scadutree Grail (10299)": LOCATION_ID_BASE + 681,
    "Shop - Grand Burning Scene (10310)": LOCATION_ID_BASE + 682,
    "Shop - Grand Tranquil Scene (10311)": LOCATION_ID_BASE + 683,
    "Murk Purse 1": LOCATION_ID_BASE + 700,
    "Murk Purse 2": LOCATION_ID_BASE + 701,
    "Murk Purse 3": LOCATION_ID_BASE + 702,
    "Murk Purse 4": LOCATION_ID_BASE + 703,
    "Murk Purse 5": LOCATION_ID_BASE + 704,
    "Murk Purse 6": LOCATION_ID_BASE + 705,
    "Murk Purse 7": LOCATION_ID_BASE + 706,
    "Murk Purse 8": LOCATION_ID_BASE + 707,
    "Murk Bundle 1": LOCATION_ID_BASE + 708,
    "Murk Bundle 2": LOCATION_ID_BASE + 709,
    "Murk Bundle 3": LOCATION_ID_BASE + 710,
    "Murk Bundle 4": LOCATION_ID_BASE + 711,
    "Murk Bundle 5": LOCATION_ID_BASE + 712,
    "Murk Bundle 6": LOCATION_ID_BASE + 713,
    "Murk Bundle 7": LOCATION_ID_BASE + 714,
    "Murk Bundle 8": LOCATION_ID_BASE + 715,
    "Murk Coffer 1": LOCATION_ID_BASE + 716,
    "Murk Coffer 2": LOCATION_ID_BASE + 717,
    "Murk Coffer 3": LOCATION_ID_BASE + 718,
    "Murk Coffer 4": LOCATION_ID_BASE + 719,
    "Murk Coffer 5": LOCATION_ID_BASE + 720,
    "Murk Coffer 6": LOCATION_ID_BASE + 721,
    "Murk Chest 1": LOCATION_ID_BASE + 722,
    "Murk Chest 2": LOCATION_ID_BASE + 723,
    "Murk Chest 3": LOCATION_ID_BASE + 724,
    "Murk Hoard 1": LOCATION_ID_BASE + 725,
    "Murk Hoard 2": LOCATION_ID_BASE + 726,
    "Nightfarer Reserve": LOCATION_ID_BASE + 600,
}

SHOP_LOCATIONS = [
    "Shop - Delicate Burning Scene (10000)",
    "Shop - Delicate Drizzly Scene (10001)",
    "Shop - Delicate Luminous Scene (10002)",
    "Shop - Delicate Tranquil Scene (10003)",
    "Shop - Polished Burning Scene (10004)",
    "Shop - Delicate Luminous Scene (10005)",
    "Shop - Polished Tranquil Scene (10010)",
    "Shop - Polished Drizzly Scene (10011)",
    "Shop - Polished Burning Scene (10012)",
    "Shop - Polished Tranquil Scene (10013)",
    "Shop - Polished Tranquil Scene (10014)",
    "Shop - Polished Burning Scene (10015)",
    "Shop - Polished Burning Scene (10020)",
    "Shop - Polished Tranquil Scene (10021)",
    "Shop - Polished Luminous Scene (10022)",
    "Shop - Polished Luminous Scene (10023)",
    "Shop - Polished Drizzly Scene (10024)",
    "Shop - Polished Drizzly Scene (10025)",
    "Shop - Grand Burning Scene (10030)",
    "Shop - Grand Drizzly Scene (10031)",
    "Shop - Grand Tranquil Scene (10032)",
    "Shop - Grand Tranquil Scene (10033)",
    "Shop - Grand Luminous Scene (10034)",
    "Shop - Grand Drizzly Scene (10035)",
    "Shop - Grand Drizzly Scene (10036)",
    "Shop - Grand Burning Scene (10037)",
    "Shop - Grand Burning Scene (10040)",
    "Shop - Grand Tranquil Scene (10041)",
    "Shop - Besmirched Frame (10100)",
    "Shop - Wylder's Goblet (10121)",
    "Shop - Guardian's Goblet (10123)",
    "Shop - Ironeye's Goblet (10125)",
    "Shop - Duchess' Goblet (10127)",
    "Shop - Raider's Goblet (10129)",
    "Shop - Revenant's Goblet (10131)",
    "Shop - Recluse's Goblet (10133)",
    "Shop - Executor's Goblet (10135)",
    "Shop - Sacred Erdtree Grail (10140)",
    "Shop - Spirit Shelter Grail (10141)",
    "Shop - Giant's Cradle Grail (10142)",
    "Shop - Polite Bow (10150)",
    "Shop - Strength (10151)",
    "Shop - Warm Welcome (10152)",
    "Shop - Fancy Spin (10153)",
    "Shop - Crossed Legs (10154)",
    "Shop - Rest (10155)",
    "Shop - Sitting Sideways (10156)",
    "Shop - Fire Spur Me (10157)",
    "Shop - As You Wish (10160)",
    "Shop - Heartening Cry (10161)",
    "Shop - Calm Down (10162)",
    "Shop - Finger Snap (10163)",
    "Shop - Prayer (10164)",
    "Shop - Rapture (10165)",
    "Shop - Erudition (10166)",
    "Shop - Outer Order (10167)",
    "Shop - Curtsy (10170)",
    "Shop - Reverential Bow (10171)",
    "Shop - Dejection (10172)",
    "Shop - Extreme Repentance (10173)",
    "Shop - Patches' Crouch (10174)",
    "Shop - Dozing Cross-Legged (10175)",
    "Shop - Desperate Prayer (10176)",
    "Shop - Hoslow's Oath (10177)",
    "Shop - Inner Order (10178)",
    "Shop - What Do You Want? (10180)",
    "Shop - My Lord (10181)",
    "Shop - Grovel For Mercy (10182)",
    "Shop - Spread Out (10183)",
    "Shop - Balled Up (10184)",
    "Shop - Golden Order Totality (10185)",
    "Shop - Prattling Pate Hello (10190)",
    "Shop - Prattling Pate Thank you (10191)",
    "Shop - Prattling Pate Wonderful (10192)",
    "Shop - Prattling Pate Please help (10193)",
    "Shop - Prattling Pate My beloved (10194)",
    "Shop - Prattling Pate Apologies (10195)",
    "Shop - Prattling Pate Let's get to it (10196)",
    "Shop - Prattling Pate You're beautiful (10197)",
    "Shop - Scholar's Goblet (10281)",
    "Shop - Undertaker's Goblet (10291)",
    "Shop - Scadutree Grail (10299)",
    "Shop - Grand Burning Scene (10310)",
    "Shop - Grand Tranquil Scene (10311)",
]

# Defeat location, expedition unlock item required to reach it.
BASE_NIGHTLORDS: List[Tuple[str, str]] = [
    ("Nightlord - Gladius", "Expedition Unlock - Tricephalos"),
    ("Nightlord - Adel", "Expedition Unlock - Adel"),
    ("Nightlord - Gnoster", "Expedition Unlock - Gnoster"),
    ("Nightlord - Maris", "Expedition Unlock - Maris"),
    ("Nightlord - Libra", "Expedition Unlock - Libra"),
    ("Nightlord - Fulghor", "Expedition Unlock - Fulghor"),
    ("Nightlord - Caligo", "Expedition Unlock - Caligo"),
]

DLC_NIGHTLORDS: List[Tuple[str, str]] = [
    ("Nightlord - Harmonia", "Expedition Unlock - Harmonia"),
    ("Nightlord - Straghess", "Expedition Unlock - Straghess"),
]

# Defeat location, Everdark unlock item. These do not count toward the Heolstor gate.
EVERDARK_NIGHTLORDS: List[Tuple[str, str]] = [
    ("Everdark - Gladius", "Everdark Unlock - Gladius"),
    ("Everdark - Adel", "Everdark Unlock - Adel"),
    ("Everdark - Gnoster", "Everdark Unlock - Gnoster"),
    ("Everdark - Maris", "Everdark Unlock - Maris"),
    ("Everdark - Libra", "Everdark Unlock - Libra"),
    ("Everdark - Fulghor", "Everdark Unlock - Fulghor"),
    ("Everdark - Caligo", "Everdark Unlock - Caligo"),
]

EVERDARK_DLC: List[Tuple[str, str]] = [
    ("Everdark - Harmonia", "Everdark Unlock - Harmonia"),
]

SPECIFIC_LOCATION = {
    "gladius": "Nightlord - Gladius",
    "adel": "Nightlord - Adel",
    "gnoster": "Nightlord - Gnoster",
    "maris": "Nightlord - Maris",
    "libra": "Nightlord - Libra",
    "fulghor": "Nightlord - Fulghor",
    "caligo": "Nightlord - Caligo",
    "heolstor": "Nightlord - Heolstor",
    "harmonia": "Nightlord - Harmonia",
    "straghess": "Nightlord - Straghess",
}
