from typing import Dict, List, Tuple

LOCATION_ID_BASE = 839_000_000

# Shop ids match flags.toml and CSFD4VirtualMemoryFlag::GetFlag on 1.3.3.0.
LOCATION_NAME_TO_ID: Dict[str, int] = {
    "Nightlord - Gladius": LOCATION_ID_BASE + 1,
    "Nightlord - Adel": LOCATION_ID_BASE + 2,
    "Nightlord - Gnoster": LOCATION_ID_BASE + 3,
    "Nightlord - Maris": LOCATION_ID_BASE + 4,
    "Nightlord - Libra": LOCATION_ID_BASE + 5,
    "Nightlord - Fulghor": LOCATION_ID_BASE + 6,
    "Nightlord - Caligo": LOCATION_ID_BASE + 7,
    "Nightlord - Heolstor": LOCATION_ID_BASE + 8,
    "Nightlord - Harmonia": LOCATION_ID_BASE + 9,
    "Nightlord - Straghess": LOCATION_ID_BASE + 10,
    "Board unlock after first Nightlord": LOCATION_ID_BASE + 100,
    "Everdark - Gladius": LOCATION_ID_BASE + 101,
    "Everdark - Adel": LOCATION_ID_BASE + 102,
    "Everdark - Gnoster": LOCATION_ID_BASE + 103,
    "Everdark - Maris": LOCATION_ID_BASE + 104,
    "Everdark - Libra": LOCATION_ID_BASE + 105,
    "Everdark - Fulghor": LOCATION_ID_BASE + 106,
    "Everdark - Caligo": LOCATION_ID_BASE + 107,
    "Everdark - Harmonia": LOCATION_ID_BASE + 108,
    "Goal - Nightlord Count": LOCATION_ID_BASE + 200,
    "Night 1 boss defeated": LOCATION_ID_BASE + 701,
    "Night 2 boss defeated": LOCATION_ID_BASE + 702,
    "Seal Evergaol 1": LOCATION_ID_BASE + 1200 + 1,
    "Seal Evergaol 2": LOCATION_ID_BASE + 1200 + 2,
    "Seal Evergaol 3": LOCATION_ID_BASE + 1200 + 3,
    "Seal Evergaol 4": LOCATION_ID_BASE + 1200 + 4,
    "Seal Evergaol 5": LOCATION_ID_BASE + 1200 + 5,
    "Seal Evergaol 6": LOCATION_ID_BASE + 1200 + 6,
    "Seal Evergaol 7": LOCATION_ID_BASE + 1200 + 7,
    "Seal Evergaol 8": LOCATION_ID_BASE + 1200 + 8,
    "Seal Evergaol 9": LOCATION_ID_BASE + 1200 + 9,
    "Seal Evergaol 10": LOCATION_ID_BASE + 1200 + 10,
    "Seal Evergaol 11": LOCATION_ID_BASE + 1200 + 11,
    "Seal Evergaol 12": LOCATION_ID_BASE + 1200 + 12,
    "Seal Evergaol 13": LOCATION_ID_BASE + 1200 + 13,
    "Seal Evergaol 14": LOCATION_ID_BASE + 1200 + 14,
    "Seal Evergaol 15": LOCATION_ID_BASE + 1200 + 15,
    "Seal Evergaol 16": LOCATION_ID_BASE + 1200 + 16,
    "Seal Evergaol 17": LOCATION_ID_BASE + 1200 + 17,
    "Seal Evergaol 18": LOCATION_ID_BASE + 1200 + 18,
    "Seal Evergaol 19": LOCATION_ID_BASE + 1200 + 19,
    "Seal Evergaol 20": LOCATION_ID_BASE + 1200 + 20,
    "Seal Evergaol 21": LOCATION_ID_BASE + 1200 + 21,
    "Seal Evergaol 22": LOCATION_ID_BASE + 1200 + 22,
    "Seal Evergaol 23": LOCATION_ID_BASE + 1200 + 23,
    "Seal Evergaol 24": LOCATION_ID_BASE + 1200 + 24,
    "Seal Evergaol 25": LOCATION_ID_BASE + 1200 + 25,
    "Seal Evergaol 26": LOCATION_ID_BASE + 1200 + 26,
    "Seal Evergaol 27": LOCATION_ID_BASE + 1200 + 27,
    "Seal Evergaol 28": LOCATION_ID_BASE + 1200 + 28,
    "Seal Evergaol 29": LOCATION_ID_BASE + 1200 + 29,
    "Seal Evergaol 30": LOCATION_ID_BASE + 1200 + 30,
    "Seal Evergaol 31": LOCATION_ID_BASE + 1200 + 31,
    "Seal Evergaol 32": LOCATION_ID_BASE + 1200 + 32,
    "Seal Evergaol 33": LOCATION_ID_BASE + 1200 + 33,
    "Seal Evergaol 34": LOCATION_ID_BASE + 1200 + 34,
    "Seal Evergaol 35": LOCATION_ID_BASE + 1200 + 35,
    "Seal Evergaol 36": LOCATION_ID_BASE + 1200 + 36,
    "Seal Evergaol 37": LOCATION_ID_BASE + 1200 + 37,
    "Seal Evergaol 38": LOCATION_ID_BASE + 1200 + 38,
    "Seal Evergaol 39": LOCATION_ID_BASE + 1200 + 39,
    "Seal Evergaol 40": LOCATION_ID_BASE + 1200 + 40,
    "Open Magician Tower 1": LOCATION_ID_BASE + 1300 + 1,
    "Open Magician Tower 2": LOCATION_ID_BASE + 1300 + 2,
    "Open Magician Tower 3": LOCATION_ID_BASE + 1300 + 3,
    "Open Magician Tower 4": LOCATION_ID_BASE + 1300 + 4,
    "Open Magician Tower 5": LOCATION_ID_BASE + 1300 + 5,
    "Open Magician Tower 6": LOCATION_ID_BASE + 1300 + 6,
    "Open Magician Tower 7": LOCATION_ID_BASE + 1300 + 7,
    "Open Magician Tower 8": LOCATION_ID_BASE + 1300 + 8,
    "Open Magician Tower 9": LOCATION_ID_BASE + 1300 + 9,
    "Open Magician Tower 10": LOCATION_ID_BASE + 1300 + 10,
    "Open Magician Tower 11": LOCATION_ID_BASE + 1300 + 11,
    "Open Magician Tower 12": LOCATION_ID_BASE + 1300 + 12,
    "Open Magician Tower 13": LOCATION_ID_BASE + 1300 + 13,
    "Open Magician Tower 14": LOCATION_ID_BASE + 1300 + 14,
    "Open Magician Tower 15": LOCATION_ID_BASE + 1300 + 15,
    "Open Magician Tower 16": LOCATION_ID_BASE + 1300 + 16,
    "Open Magician Tower 17": LOCATION_ID_BASE + 1300 + 17,
    "Open Magician Tower 18": LOCATION_ID_BASE + 1300 + 18,
    "Open Magician Tower 19": LOCATION_ID_BASE + 1300 + 19,
    "Open Magician Tower 20": LOCATION_ID_BASE + 1300 + 20,
    "Open Magician Tower 21": LOCATION_ID_BASE + 1300 + 21,
    "Open Magician Tower 22": LOCATION_ID_BASE + 1300 + 22,
    "Open Magician Tower 23": LOCATION_ID_BASE + 1300 + 23,
    "Open Magician Tower 24": LOCATION_ID_BASE + 1300 + 24,
    "Open Magician Tower 25": LOCATION_ID_BASE + 1300 + 25,
    "Open Magician Tower 26": LOCATION_ID_BASE + 1300 + 26,
    "Open Magician Tower 27": LOCATION_ID_BASE + 1300 + 27,
    "Open Magician Tower 28": LOCATION_ID_BASE + 1300 + 28,
    "Open Magician Tower 29": LOCATION_ID_BASE + 1300 + 29,
    "Open Magician Tower 30": LOCATION_ID_BASE + 1300 + 30,
    "Day 1 Boss 1": LOCATION_ID_BASE + 1000 + 1,
    "Day 1 Boss 2": LOCATION_ID_BASE + 1000 + 2,
    "Day 1 Boss 3": LOCATION_ID_BASE + 1000 + 3,
    "Day 1 Boss 4": LOCATION_ID_BASE + 1000 + 4,
    "Day 1 Boss 5": LOCATION_ID_BASE + 1000 + 5,
    "Day 1 Boss 6": LOCATION_ID_BASE + 1000 + 6,
    "Day 1 Boss 7": LOCATION_ID_BASE + 1000 + 7,
    "Day 1 Boss 8": LOCATION_ID_BASE + 1000 + 8,
    "Day 1 Boss 9": LOCATION_ID_BASE + 1000 + 9,
    "Day 1 Boss 10": LOCATION_ID_BASE + 1000 + 10,
    "Day 1 Boss 11": LOCATION_ID_BASE + 1000 + 11,
    "Day 1 Boss 12": LOCATION_ID_BASE + 1000 + 12,
    "Day 1 Boss 13": LOCATION_ID_BASE + 1000 + 13,
    "Day 1 Boss 14": LOCATION_ID_BASE + 1000 + 14,
    "Day 1 Boss 15": LOCATION_ID_BASE + 1000 + 15,
    "Day 1 Boss 16": LOCATION_ID_BASE + 1000 + 16,
    "Day 1 Boss 17": LOCATION_ID_BASE + 1000 + 17,
    "Day 1 Boss 18": LOCATION_ID_BASE + 1000 + 18,
    "Day 1 Boss 19": LOCATION_ID_BASE + 1000 + 19,
    "Day 1 Boss 20": LOCATION_ID_BASE + 1000 + 20,
    "Day 1 Boss 21": LOCATION_ID_BASE + 1000 + 21,
    "Day 1 Boss 22": LOCATION_ID_BASE + 1000 + 22,
    "Day 1 Boss 23": LOCATION_ID_BASE + 1000 + 23,
    "Day 1 Boss 24": LOCATION_ID_BASE + 1000 + 24,
    "Day 1 Boss 25": LOCATION_ID_BASE + 1000 + 25,
    "Day 1 Boss 26": LOCATION_ID_BASE + 1000 + 26,
    "Day 1 Boss 27": LOCATION_ID_BASE + 1000 + 27,
    "Day 1 Boss 28": LOCATION_ID_BASE + 1000 + 28,
    "Day 1 Boss 29": LOCATION_ID_BASE + 1000 + 29,
    "Day 1 Boss 30": LOCATION_ID_BASE + 1000 + 30,
    "Day 2 Boss 1": LOCATION_ID_BASE + 1100 + 1,
    "Day 2 Boss 2": LOCATION_ID_BASE + 1100 + 2,
    "Day 2 Boss 3": LOCATION_ID_BASE + 1100 + 3,
    "Day 2 Boss 4": LOCATION_ID_BASE + 1100 + 4,
    "Day 2 Boss 5": LOCATION_ID_BASE + 1100 + 5,
    "Day 2 Boss 6": LOCATION_ID_BASE + 1100 + 6,
    "Day 2 Boss 7": LOCATION_ID_BASE + 1100 + 7,
    "Day 2 Boss 8": LOCATION_ID_BASE + 1100 + 8,
    "Day 2 Boss 9": LOCATION_ID_BASE + 1100 + 9,
    "Day 2 Boss 10": LOCATION_ID_BASE + 1100 + 10,
    "Day 2 Boss 11": LOCATION_ID_BASE + 1100 + 11,
    "Day 2 Boss 12": LOCATION_ID_BASE + 1100 + 12,
    "Day 2 Boss 13": LOCATION_ID_BASE + 1100 + 13,
    "Day 2 Boss 14": LOCATION_ID_BASE + 1100 + 14,
    "Day 2 Boss 15": LOCATION_ID_BASE + 1100 + 15,
    "Day 2 Boss 16": LOCATION_ID_BASE + 1100 + 16,
    "Day 2 Boss 17": LOCATION_ID_BASE + 1100 + 17,
    "Day 2 Boss 18": LOCATION_ID_BASE + 1100 + 18,
    "Day 2 Boss 19": LOCATION_ID_BASE + 1100 + 19,
    "Day 2 Boss 20": LOCATION_ID_BASE + 1100 + 20,
    "Day 2 Boss 21": LOCATION_ID_BASE + 1100 + 21,
    "Day 2 Boss 22": LOCATION_ID_BASE + 1100 + 22,
    "Day 2 Boss 23": LOCATION_ID_BASE + 1100 + 23,
    "Day 2 Boss 24": LOCATION_ID_BASE + 1100 + 24,
    "Day 2 Boss 25": LOCATION_ID_BASE + 1100 + 25,
    "Day 2 Boss 26": LOCATION_ID_BASE + 1100 + 26,
    "Day 2 Boss 27": LOCATION_ID_BASE + 1100 + 27,
    "Day 2 Boss 28": LOCATION_ID_BASE + 1100 + 28,
    "Day 2 Boss 29": LOCATION_ID_BASE + 1100 + 29,
    "Day 2 Boss 30": LOCATION_ID_BASE + 1100 + 30,
    'Shop - Prattling Pate Hello': LOCATION_ID_BASE + + 548,
    'Shop - Prattling Pate Thank you': LOCATION_ID_BASE + + 549,
    'Shop - Prattling Pate Wonderful': LOCATION_ID_BASE + + 550,
    'Shop - Prattling Pate Please help': LOCATION_ID_BASE + + 551,
    'Shop - Prattling Pate My beloved': LOCATION_ID_BASE + + 552,
    'Shop - Prattling Pate Apologies': LOCATION_ID_BASE + + 553,
    'Shop - Prattling Pate Lets get to it': LOCATION_ID_BASE + + 554,
    'Shop - Prattling Pate Youre beautiful': LOCATION_ID_BASE + + 555,
    "Shop - Delicate Burning Scene": LOCATION_ID_BASE + 600,
    "Shop - Delicate Drizzly Scene": LOCATION_ID_BASE + 601,
    "Shop - Delicate Luminous Scene 1": LOCATION_ID_BASE + 602,
    "Shop - Delicate Tranquil Scene": LOCATION_ID_BASE + 603,
    "Shop - Polished Burning Scene 1": LOCATION_ID_BASE + 604,
    "Shop - Delicate Luminous Scene 2": LOCATION_ID_BASE + 605,
    "Shop - Polished Tranquil Scene 1": LOCATION_ID_BASE + 606,
    "Shop - Polished Drizzly Scene 1": LOCATION_ID_BASE + 607,
    "Shop - Polished Burning Scene 2": LOCATION_ID_BASE + 608,
    "Shop - Polished Tranquil Scene 2": LOCATION_ID_BASE + 609,
    "Shop - Polished Tranquil Scene 3": LOCATION_ID_BASE + 610,
    "Shop - Polished Burning Scene 3": LOCATION_ID_BASE + 611,
    "Shop - Polished Burning Scene 4": LOCATION_ID_BASE + 612,
    "Shop - Polished Tranquil Scene 4": LOCATION_ID_BASE + 613,
    "Shop - Polished Luminous Scene 1": LOCATION_ID_BASE + 614,
    "Shop - Polished Luminous Scene 2": LOCATION_ID_BASE + 615,
    "Shop - Polished Drizzly Scene 2": LOCATION_ID_BASE + 616,
    "Shop - Polished Drizzly Scene 3": LOCATION_ID_BASE + 617,
    "Shop - Grand Burning Scene 1": LOCATION_ID_BASE + 618,
    "Shop - Grand Drizzly Scene 1": LOCATION_ID_BASE + 619,
    "Shop - Grand Tranquil Scene 1": LOCATION_ID_BASE + 620,
    "Shop - Grand Tranquil Scene 2": LOCATION_ID_BASE + 621,
    "Shop - Grand Luminous Scene": LOCATION_ID_BASE + 622,
    "Shop - Grand Drizzly Scene 2": LOCATION_ID_BASE + 623,
    "Shop - Grand Drizzly Scene 3": LOCATION_ID_BASE + 624,
    "Shop - Grand Burning Scene 2": LOCATION_ID_BASE + 625,
    "Shop - Grand Burning Scene 3": LOCATION_ID_BASE + 626,
    "Shop - Grand Tranquil Scene 3": LOCATION_ID_BASE + 627,
    "Shop - Besmirched Frame": LOCATION_ID_BASE + 628,
    "Shop - Wylder's Goblet": LOCATION_ID_BASE + 629,
    "Shop - Guardian's Goblet": LOCATION_ID_BASE + 630,
    "Shop - Ironeye's Goblet": LOCATION_ID_BASE + 631,
    "Shop - Duchess' Goblet": LOCATION_ID_BASE + 632,
    "Shop - Raider's Goblet": LOCATION_ID_BASE + 633,
    "Shop - Revenant's Goblet": LOCATION_ID_BASE + 634,
    "Shop - Recluse's Goblet": LOCATION_ID_BASE + 635,
    "Shop - Executor's Goblet": LOCATION_ID_BASE + 636,
    "Shop - Sacred Erdtree Grail": LOCATION_ID_BASE + 637,
    "Shop - Spirit Shelter Grail": LOCATION_ID_BASE + 638,
    "Shop - Giant's Cradle Grail": LOCATION_ID_BASE + 639,
    "Shop - Polite Bow": LOCATION_ID_BASE + 640,
    "Shop - Strength": LOCATION_ID_BASE + 641,
    "Shop - Warm Welcome": LOCATION_ID_BASE + 642,
    "Shop - Fancy Spin": LOCATION_ID_BASE + 643,
    "Shop - Crossed Legs": LOCATION_ID_BASE + 644,
    "Shop - Rest": LOCATION_ID_BASE + 645,
    "Shop - Sitting Sideways": LOCATION_ID_BASE + 646,
    "Shop - Fire Spur Me": LOCATION_ID_BASE + 647,
    "Shop - As You Wish": LOCATION_ID_BASE + 648,
    "Shop - Heartening Cry": LOCATION_ID_BASE + 649,
    "Shop - Calm Down": LOCATION_ID_BASE + 650,
    "Shop - Finger Snap": LOCATION_ID_BASE + 651,
    "Shop - Prayer": LOCATION_ID_BASE + 652,
    "Shop - Rapture": LOCATION_ID_BASE + 653,
    "Shop - Erudition": LOCATION_ID_BASE + 654,
    "Shop - Outer Order": LOCATION_ID_BASE + 655,
    "Shop - Curtsy": LOCATION_ID_BASE + 656,
    "Shop - Reverential Bow": LOCATION_ID_BASE + 657,
    "Shop - Dejection": LOCATION_ID_BASE + 658,
    "Shop - Extreme Repentance": LOCATION_ID_BASE + 659,
    "Shop - Patches' Crouch": LOCATION_ID_BASE + 660,
    "Shop - Dozing Cross-Legged": LOCATION_ID_BASE + 661,
    "Shop - Desperate Prayer": LOCATION_ID_BASE + 662,
    "Shop - Hoslow's Oath": LOCATION_ID_BASE + 663,
    "Shop - Inner Order": LOCATION_ID_BASE + 664,
    "Shop - What Do You Want?": LOCATION_ID_BASE + 665,
    "Shop - My Lord": LOCATION_ID_BASE + 666,
    "Shop - Grovel For Mercy": LOCATION_ID_BASE + 667,
    "Shop - Spread Out": LOCATION_ID_BASE + 668,
    "Shop - Balled Up": LOCATION_ID_BASE + 669,
    "Shop - Golden Order Totality": LOCATION_ID_BASE + 670,
    "Shop - Prattling Pate Hello": LOCATION_ID_BASE + 671,
    "Shop - Prattling Pate Thank you": LOCATION_ID_BASE + 672,
    "Shop - Prattling Pate Wonderful": LOCATION_ID_BASE + 673,
    "Shop - Prattling Pate Please help": LOCATION_ID_BASE + 674,
    "Shop - Prattling Pate My beloved": LOCATION_ID_BASE + 675,
    "Shop - Prattling Pate Apologies": LOCATION_ID_BASE + 676,
    "Shop - Prattling Pate Let's get to it": LOCATION_ID_BASE + 677,
    "Shop - Prattling Pate You're beautiful": LOCATION_ID_BASE + 678,
    "Shop - Scholar's Goblet": LOCATION_ID_BASE + 679,
    "Shop - Undertaker's Goblet": LOCATION_ID_BASE + 680,
    "Shop - Scadutree Grail": LOCATION_ID_BASE + 681,
    "Shop - Grand Burning Scene 4": LOCATION_ID_BASE + 682,
    "Shop - Grand Tranquil Scene 4": LOCATION_ID_BASE + 683,
    "Murk 1": LOCATION_ID_BASE + 700,
    "Murk 2": LOCATION_ID_BASE + 701,
    "Murk 3": LOCATION_ID_BASE + 702,
    "Murk 4": LOCATION_ID_BASE + 703,
    "Murk 5": LOCATION_ID_BASE + 704,
    "Murk 6": LOCATION_ID_BASE + 705,
    "Murk 7": LOCATION_ID_BASE + 706,
    "Murk 8": LOCATION_ID_BASE + 707,
    "Murk 9": LOCATION_ID_BASE + 708,
    "Murk 10": LOCATION_ID_BASE + 709,
    "Murk 11": LOCATION_ID_BASE + 710,
    "Murk 12": LOCATION_ID_BASE + 711,
    "Murk 13": LOCATION_ID_BASE + 712,
    "Murk 14": LOCATION_ID_BASE + 713,
    "Murk 15": LOCATION_ID_BASE + 714,
    "Murk 16": LOCATION_ID_BASE + 715,
    "Murk 17": LOCATION_ID_BASE + 716,
    "Murk 18": LOCATION_ID_BASE + 717,
    "Murk 19": LOCATION_ID_BASE + 718,
    "Murk 20": LOCATION_ID_BASE + 719,
    "Murk 21": LOCATION_ID_BASE + 720,
    "Murk 22": LOCATION_ID_BASE + 721,
    "Murk 23": LOCATION_ID_BASE + 722,
    "Murk 24": LOCATION_ID_BASE + 723,
    "Murk 25": LOCATION_ID_BASE + 724,
    "Murk 26": LOCATION_ID_BASE + 725,
    "Murk 27": LOCATION_ID_BASE + 726,
    "Bosses Killed (1)": LOCATION_ID_BASE + 801,
    "Bosses Killed (3)": LOCATION_ID_BASE + 803,
    "Bosses Killed (5)": LOCATION_ID_BASE + 805,
    "Bosses Killed (10)": LOCATION_ID_BASE + 810,
    "Bosses Killed (20)": LOCATION_ID_BASE + 820,
    "Nightfarer Reserve": LOCATION_ID_BASE + 600,
}

SHOP_LOCATIONS = [
    "Shop - Delicate Burning Scene",
    "Shop - Delicate Drizzly Scene",
    "Shop - Delicate Luminous Scene 1",
    "Shop - Delicate Tranquil Scene",
    "Shop - Polished Burning Scene 1",
    "Shop - Delicate Luminous Scene 2",
    "Shop - Polished Tranquil Scene 1",
    "Shop - Polished Drizzly Scene 1",
    "Shop - Polished Burning Scene 2",
    "Shop - Polished Tranquil Scene 2",
    "Shop - Polished Tranquil Scene 3",
    "Shop - Polished Burning Scene 3",
    "Shop - Polished Burning Scene 4",
    "Shop - Polished Tranquil Scene 4",
    "Shop - Polished Luminous Scene 1",
    "Shop - Polished Luminous Scene 2",
    "Shop - Polished Drizzly Scene 2",
    "Shop - Polished Drizzly Scene 3",
    "Shop - Grand Burning Scene 1",
    "Shop - Grand Drizzly Scene 1",
    "Shop - Grand Tranquil Scene 1",
    "Shop - Grand Tranquil Scene 2",
    "Shop - Grand Luminous Scene",
    "Shop - Grand Drizzly Scene 2",
    "Shop - Grand Drizzly Scene 3",
    "Shop - Grand Burning Scene 2",
    "Shop - Grand Burning Scene 3",
    "Shop - Grand Tranquil Scene 3",
    "Shop - Besmirched Frame",
    "Shop - Wylder's Goblet",
    "Shop - Guardian's Goblet",
    "Shop - Ironeye's Goblet",
    "Shop - Duchess' Goblet",
    "Shop - Raider's Goblet",
    "Shop - Revenant's Goblet",
    "Shop - Recluse's Goblet",
    "Shop - Executor's Goblet",
    "Shop - Sacred Erdtree Grail",
    "Shop - Spirit Shelter Grail",
    "Shop - Giant's Cradle Grail",
    "Shop - Polite Bow",
    "Shop - Strength",
    "Shop - Warm Welcome",
    "Shop - Fancy Spin",
    "Shop - Crossed Legs",
    "Shop - Rest",
    "Shop - Sitting Sideways",
    "Shop - Fire Spur Me",
    "Shop - As You Wish",
    "Shop - Heartening Cry",
    "Shop - Calm Down",
    "Shop - Finger Snap",
    "Shop - Prayer",
    "Shop - Rapture",
    "Shop - Erudition",
    "Shop - Outer Order",
    "Shop - Curtsy",
    "Shop - Reverential Bow",
    "Shop - Dejection",
    "Shop - Extreme Repentance",
    "Shop - Patches' Crouch",
    "Shop - Dozing Cross-Legged",
    "Shop - Desperate Prayer",
    "Shop - Hoslow's Oath",
    "Shop - Inner Order",
    "Shop - What Do You Want?",
    "Shop - My Lord",
    "Shop - Grovel For Mercy",
    "Shop - Spread Out",
    "Shop - Balled Up",
    "Shop - Golden Order Totality",
    "Shop - Prattling Pate Hello",
    "Shop - Prattling Pate Thank you",
    "Shop - Prattling Pate Wonderful",
    "Shop - Prattling Pate Please help",
    "Shop - Prattling Pate My beloved",
    "Shop - Prattling Pate Apologies",
    "Shop - Prattling Pate Let's get to it",
    "Shop - Prattling Pate You're beautiful",
    "Shop - Scholar's Goblet",
    "Shop - Undertaker's Goblet",
    "Shop - Scadutree Grail",
    "Shop - Grand Burning Scene 4",
    "Shop - Grand Tranquil Scene 4",
]

# Defeat location, expedition unlock item required to reach it.
BASE_NIGHTLORDS: List[Tuple[str, str]] = [
    ("Nightlord - Gladius", "Expedition Unlock - Tricephalos"),
    ("Nightlord - Adel", "Expedition Unlock - Adel"),
    ("Nightlord - Gnoster", "Expedition Unlock - Gnoster"),
    ("Nightlord - Maris", "Expedition Unlock - Maris"),
    ("Nightlord - Libra", "Expedition Unlock - Libra"),
    ("Nightlord - Fulghor", "Expedition Unlock - Fulghor"),
    ("Nightlord - Caligo", "Expedition Unlock - Caligo"),
]

DLC_NIGHTLORDS: List[Tuple[str, str]] = [
    ("Nightlord - Harmonia", "Expedition Unlock - Harmonia"),
    ("Nightlord - Straghess", "Expedition Unlock - Straghess"),
]

# Defeat location, Everdark unlock item. These do not count toward the Heolstor gate.
EVERDARK_NIGHTLORDS: List[Tuple[str, str]] = [
    ("Everdark - Gladius", "Everdark Unlock - Gladius"),
    ("Everdark - Adel", "Everdark Unlock - Adel"),
    ("Everdark - Gnoster", "Everdark Unlock - Gnoster"),
    ("Everdark - Maris", "Everdark Unlock - Maris"),
    ("Everdark - Libra", "Everdark Unlock - Libra"),
    ("Everdark - Fulghor", "Everdark Unlock - Fulghor"),
    ("Everdark - Caligo", "Everdark Unlock - Caligo"),
]

EVERDARK_DLC: List[Tuple[str, str]] = [
    ("Everdark - Harmonia", "Everdark Unlock - Harmonia"),
]

SPECIFIC_LOCATION = {
    "gladius": "Nightlord - Gladius",
    "adel": "Nightlord - Adel",
    "gnoster": "Nightlord - Gnoster",
    "maris": "Nightlord - Maris",
    "libra": "Nightlord - Libra",
    "fulghor": "Nightlord - Fulghor",
    "caligo": "Nightlord - Caligo",
    "heolstor": "Nightlord - Heolstor",
    "harmonia": "Nightlord - Harmonia",
    "straghess": "Nightlord - Straghess",
}
