from typing import Dict, List, Tuple

LOCATION_ID_BASE = 839_000_000

# Shop ids match flags.toml and CSFD4VirtualMemoryFlag::GetFlag on 1.3.3.0.
LOCATION_NAME_TO_ID: Dict[str, int] = {
    "Nightlord - Gladius": LOCATION_ID_BASE + 1,
    "Nightlord - Adel": LOCATION_ID_BASE + 2,
    "Nightlord - Gnoster": LOCATION_ID_BASE + 3,
    "Nightlord - Maris": LOCATION_ID_BASE + 4,
    "Nightlord - Libra": LOCATION_ID_BASE + 5,
    "Nightlord - Fulghor": LOCATION_ID_BASE + 6,
    "Nightlord - Caligo": LOCATION_ID_BASE + 7,
    "Nightlord - Heolstor": LOCATION_ID_BASE + 8,
    "Nightlord - Harmonia": LOCATION_ID_BASE + 9,
    "Nightlord - Straghess": LOCATION_ID_BASE + 10,
    "Board unlock after first Nightlord": LOCATION_ID_BASE + 100,
    "Defeat Tutorial Margit": LOCATION_ID_BASE + 210,
    "Unlock Duchess": LOCATION_ID_BASE + 401,
    "Unlock Revenant": LOCATION_ID_BASE + 402,
    "Unlock Scholar": LOCATION_ID_BASE + 403,
    "Unlock Undertaker": LOCATION_ID_BASE + 404,
    "Everdark - Gladius": LOCATION_ID_BASE + 101,
    "Everdark - Adel": LOCATION_ID_BASE + 102,
    "Everdark - Gnoster": LOCATION_ID_BASE + 103,
    "Everdark - Maris": LOCATION_ID_BASE + 104,
    "Everdark - Libra": LOCATION_ID_BASE + 105,
    "Everdark - Fulghor": LOCATION_ID_BASE + 106,
    "Everdark - Caligo": LOCATION_ID_BASE + 107,
    "Everdark - Harmonia": LOCATION_ID_BASE + 108,
    "Goal - Nightlord Count": LOCATION_ID_BASE + 200,
    "Night 1 boss defeated": LOCATION_ID_BASE + 701,
    "Night 2 boss defeated": LOCATION_ID_BASE + 702,
    "Seal Evergaol 1": LOCATION_ID_BASE + 1200 + 1,
    "Seal Evergaol 2": LOCATION_ID_BASE + 1200 + 2,
    "Seal Evergaol 3": LOCATION_ID_BASE + 1200 + 3,
    "Seal Evergaol 4": LOCATION_ID_BASE + 1200 + 4,
    "Seal Evergaol 5": LOCATION_ID_BASE + 1200 + 5,
    "Seal Evergaol 6": LOCATION_ID_BASE + 1200 + 6,
    "Seal Evergaol 7": LOCATION_ID_BASE + 1200 + 7,
    "Seal Evergaol 8": LOCATION_ID_BASE + 1200 + 8,
    "Seal Evergaol 9": LOCATION_ID_BASE + 1200 + 9,
    "Seal Evergaol 10": LOCATION_ID_BASE + 1200 + 10,
    "Seal Evergaol 11": LOCATION_ID_BASE + 1200 + 11,
    "Seal Evergaol 12": LOCATION_ID_BASE + 1200 + 12,
    "Seal Evergaol 13": LOCATION_ID_BASE + 1200 + 13,
    "Seal Evergaol 14": LOCATION_ID_BASE + 1200 + 14,
    "Seal Evergaol 15": LOCATION_ID_BASE + 1200 + 15,
    "Seal Evergaol 16": LOCATION_ID_BASE + 1200 + 16,
    "Seal Evergaol 17": LOCATION_ID_BASE + 1200 + 17,
    "Seal Evergaol 18": LOCATION_ID_BASE + 1200 + 18,
    "Seal Evergaol 19": LOCATION_ID_BASE + 1200 + 19,
    "Seal Evergaol 20": LOCATION_ID_BASE + 1200 + 20,
    "Seal Evergaol 21": LOCATION_ID_BASE + 1200 + 21,
    "Seal Evergaol 22": LOCATION_ID_BASE + 1200 + 22,
    "Seal Evergaol 23": LOCATION_ID_BASE + 1200 + 23,
    "Seal Evergaol 24": LOCATION_ID_BASE + 1200 + 24,
    "Seal Evergaol 25": LOCATION_ID_BASE + 1200 + 25,
    "Seal Evergaol 26": LOCATION_ID_BASE + 1200 + 26,
    "Seal Evergaol 27": LOCATION_ID_BASE + 1200 + 27,
    "Seal Evergaol 28": LOCATION_ID_BASE + 1200 + 28,
    "Seal Evergaol 29": LOCATION_ID_BASE + 1200 + 29,
    "Seal Evergaol 30": LOCATION_ID_BASE + 1200 + 30,
    "Seal Evergaol 31": LOCATION_ID_BASE + 1200 + 31,
    "Seal Evergaol 32": LOCATION_ID_BASE + 1200 + 32,
    "Seal Evergaol 33": LOCATION_ID_BASE + 1200 + 33,
    "Seal Evergaol 34": LOCATION_ID_BASE + 1200 + 34,
    "Seal Evergaol 35": LOCATION_ID_BASE + 1200 + 35,
    "Seal Evergaol 36": LOCATION_ID_BASE + 1200 + 36,
    "Seal Evergaol 37": LOCATION_ID_BASE + 1200 + 37,
    "Seal Evergaol 38": LOCATION_ID_BASE + 1200 + 38,
    "Seal Evergaol 39": LOCATION_ID_BASE + 1200 + 39,
    "Seal Evergaol 40": LOCATION_ID_BASE + 1200 + 40,
    "Open Magician Tower 1": LOCATION_ID_BASE + 1300 + 1,
    "Open Magician Tower 2": LOCATION_ID_BASE + 1300 + 2,
    "Open Magician Tower 3": LOCATION_ID_BASE + 1300 + 3,
    "Open Magician Tower 4": LOCATION_ID_BASE + 1300 + 4,
    "Open Magician Tower 5": LOCATION_ID_BASE + 1300 + 5,
    "Open Magician Tower 6": LOCATION_ID_BASE + 1300 + 6,
    "Open Magician Tower 7": LOCATION_ID_BASE + 1300 + 7,
    "Open Magician Tower 8": LOCATION_ID_BASE + 1300 + 8,
    "Open Magician Tower 9": LOCATION_ID_BASE + 1300 + 9,
    "Open Magician Tower 10": LOCATION_ID_BASE + 1300 + 10,
    "Open Magician Tower 11": LOCATION_ID_BASE + 1300 + 11,
    "Open Magician Tower 12": LOCATION_ID_BASE + 1300 + 12,
    "Open Magician Tower 13": LOCATION_ID_BASE + 1300 + 13,
    "Open Magician Tower 14": LOCATION_ID_BASE + 1300 + 14,
    "Open Magician Tower 15": LOCATION_ID_BASE + 1300 + 15,
    "Open Magician Tower 16": LOCATION_ID_BASE + 1300 + 16,
    "Open Magician Tower 17": LOCATION_ID_BASE + 1300 + 17,
    "Open Magician Tower 18": LOCATION_ID_BASE + 1300 + 18,
    "Open Magician Tower 19": LOCATION_ID_BASE + 1300 + 19,
    "Open Magician Tower 20": LOCATION_ID_BASE + 1300 + 20,
    "Open Magician Tower 21": LOCATION_ID_BASE + 1300 + 21,
    "Open Magician Tower 22": LOCATION_ID_BASE + 1300 + 22,
    "Open Magician Tower 23": LOCATION_ID_BASE + 1300 + 23,
    "Open Magician Tower 24": LOCATION_ID_BASE + 1300 + 24,
    "Open Magician Tower 25": LOCATION_ID_BASE + 1300 + 25,
    "Open Magician Tower 26": LOCATION_ID_BASE + 1300 + 26,
    "Open Magician Tower 27": LOCATION_ID_BASE + 1300 + 27,
    "Open Magician Tower 28": LOCATION_ID_BASE + 1300 + 28,
    "Open Magician Tower 29": LOCATION_ID_BASE + 1300 + 29,
    "Open Magician Tower 30": LOCATION_ID_BASE + 1300 + 30,
    "Open Magician Tower 31": LOCATION_ID_BASE + 1300 + 31,
    "Open Magician Tower 32": LOCATION_ID_BASE + 1300 + 32,
    "Open Magician Tower 33": LOCATION_ID_BASE + 1300 + 33,
    "Open Magician Tower 34": LOCATION_ID_BASE + 1300 + 34,
    "Open Magician Tower 35": LOCATION_ID_BASE + 1300 + 35,
    "Open Magician Tower 36": LOCATION_ID_BASE + 1300 + 36,
    "Open Magician Tower 37": LOCATION_ID_BASE + 1300 + 37,
    "Open Magician Tower 38": LOCATION_ID_BASE + 1300 + 38,
    "Open Magician Tower 39": LOCATION_ID_BASE + 1300 + 39,
    "Open Magician Tower 40": LOCATION_ID_BASE + 1300 + 40,
    "Open Magician Tower 41": LOCATION_ID_BASE + 1300 + 41,
    "Open Magician Tower 42": LOCATION_ID_BASE + 1300 + 42,
    "Open Magician Tower 43": LOCATION_ID_BASE + 1300 + 43,
    "Open Magician Tower 44": LOCATION_ID_BASE + 1300 + 44,
    "Open Magician Tower 45": LOCATION_ID_BASE + 1300 + 45,
    "Open Magician Tower 46": LOCATION_ID_BASE + 1300 + 46,
    "Open Magician Tower 47": LOCATION_ID_BASE + 1300 + 47,
    "Open Magician Tower 48": LOCATION_ID_BASE + 1300 + 48,
    "Open Magician Tower 49": LOCATION_ID_BASE + 1300 + 49,
    "Open Magician Tower 50": LOCATION_ID_BASE + 1300 + 50,
    "Defeat Invaders 1": LOCATION_ID_BASE + 1400 + 1,
    "Defeat Invaders 2": LOCATION_ID_BASE + 1400 + 2,
    "Defeat Invaders 3": LOCATION_ID_BASE + 1400 + 3,
    "Defeat Invaders 4": LOCATION_ID_BASE + 1400 + 4,
    "Defeat Invaders 5": LOCATION_ID_BASE + 1400 + 5,
    "Defeat Invaders 6": LOCATION_ID_BASE + 1400 + 6,
    "Defeat Invaders 7": LOCATION_ID_BASE + 1400 + 7,
    "Defeat Invaders 8": LOCATION_ID_BASE + 1400 + 8,
    "Defeat Invaders 9": LOCATION_ID_BASE + 1400 + 9,
    "Defeat Invaders 10": LOCATION_ID_BASE + 1400 + 10,
    "Defeat Invaders 11": LOCATION_ID_BASE + 1400 + 11,
    "Defeat Invaders 12": LOCATION_ID_BASE + 1400 + 12,
    "Defeat Invaders 13": LOCATION_ID_BASE + 1400 + 13,
    "Defeat Invaders 14": LOCATION_ID_BASE + 1400 + 14,
    "Defeat Invaders 15": LOCATION_ID_BASE + 1400 + 15,
    "Defeat Invaders 16": LOCATION_ID_BASE + 1400 + 16,
    "Defeat Invaders 17": LOCATION_ID_BASE + 1400 + 17,
    "Defeat Invaders 18": LOCATION_ID_BASE + 1400 + 18,
    "Defeat Invaders 19": LOCATION_ID_BASE + 1400 + 19,
    "Defeat Invaders 20": LOCATION_ID_BASE + 1400 + 20,
    "Defeat Invaders 21": LOCATION_ID_BASE + 1400 + 21,
    "Defeat Invaders 22": LOCATION_ID_BASE + 1400 + 22,
    "Defeat Invaders 23": LOCATION_ID_BASE + 1400 + 23,
    "Defeat Invaders 24": LOCATION_ID_BASE + 1400 + 24,
    "Defeat Invaders 25": LOCATION_ID_BASE + 1400 + 25,
    "Defeat Invaders 26": LOCATION_ID_BASE + 1400 + 26,
    "Defeat Invaders 27": LOCATION_ID_BASE + 1400 + 27,
    "Defeat Invaders 28": LOCATION_ID_BASE + 1400 + 28,
    "Defeat Invaders 29": LOCATION_ID_BASE + 1400 + 29,
    "Defeat Invaders 30": LOCATION_ID_BASE + 1400 + 30,
    "Defeat Invaders 31": LOCATION_ID_BASE + 1400 + 31,
    "Defeat Invaders 32": LOCATION_ID_BASE + 1400 + 32,
    "Defeat Invaders 33": LOCATION_ID_BASE + 1400 + 33,
    "Defeat Invaders 34": LOCATION_ID_BASE + 1400 + 34,
    "Defeat Invaders 35": LOCATION_ID_BASE + 1400 + 35,
    "Defeat Invaders 36": LOCATION_ID_BASE + 1400 + 36,
    "Defeat Invaders 37": LOCATION_ID_BASE + 1400 + 37,
    "Defeat Invaders 38": LOCATION_ID_BASE + 1400 + 38,
    "Defeat Invaders 39": LOCATION_ID_BASE + 1400 + 39,
    "Defeat Invaders 40": LOCATION_ID_BASE + 1400 + 40,
    "Defeat Invaders 41": LOCATION_ID_BASE + 1400 + 41,
    "Defeat Invaders 42": LOCATION_ID_BASE + 1400 + 42,
    "Defeat Invaders 43": LOCATION_ID_BASE + 1400 + 43,
    "Defeat Invaders 44": LOCATION_ID_BASE + 1400 + 44,
    "Defeat Invaders 45": LOCATION_ID_BASE + 1400 + 45,
    "Defeat Invaders 46": LOCATION_ID_BASE + 1400 + 46,
    "Defeat Invaders 47": LOCATION_ID_BASE + 1400 + 47,
    "Defeat Invaders 48": LOCATION_ID_BASE + 1400 + 48,
    "Defeat Invaders 49": LOCATION_ID_BASE + 1400 + 49,
    "Defeat Invaders 50": LOCATION_ID_BASE + 1400 + 50,
    "Buried Treasure Map 1": LOCATION_ID_BASE + 1500 + 1,
    "Buried Treasure Map 2": LOCATION_ID_BASE + 1500 + 2,
    "Buried Treasure Map 3": LOCATION_ID_BASE + 1500 + 3,
    "Buried Treasure Map 4": LOCATION_ID_BASE + 1500 + 4,
    "Buried Treasure Map 5": LOCATION_ID_BASE + 1500 + 5,
    "Buried Treasure Map 6": LOCATION_ID_BASE + 1500 + 6,
    "Buried Treasure Map 7": LOCATION_ID_BASE + 1500 + 7,
    "Buried Treasure Map 8": LOCATION_ID_BASE + 1500 + 8,
    "Buried Treasure Map 9": LOCATION_ID_BASE + 1500 + 9,
    "Buried Treasure Map 10": LOCATION_ID_BASE + 1500 + 10,
    "Buried Treasure Map 11": LOCATION_ID_BASE + 1500 + 11,
    "Buried Treasure Map 12": LOCATION_ID_BASE + 1500 + 12,
    "Buried Treasure Map 13": LOCATION_ID_BASE + 1500 + 13,
    "Buried Treasure Map 14": LOCATION_ID_BASE + 1500 + 14,
    "Buried Treasure Map 15": LOCATION_ID_BASE + 1500 + 15,
    "Buried Treasure Map 16": LOCATION_ID_BASE + 1500 + 16,
    "Buried Treasure Map 17": LOCATION_ID_BASE + 1500 + 17,
    "Buried Treasure Map 18": LOCATION_ID_BASE + 1500 + 18,
    "Buried Treasure Map 19": LOCATION_ID_BASE + 1500 + 19,
    "Buried Treasure Map 20": LOCATION_ID_BASE + 1500 + 20,
    "Buried Treasure Map 21": LOCATION_ID_BASE + 1500 + 21,
    "Buried Treasure Map 22": LOCATION_ID_BASE + 1500 + 22,
    "Buried Treasure Map 23": LOCATION_ID_BASE + 1500 + 23,
    "Buried Treasure Map 24": LOCATION_ID_BASE + 1500 + 24,
    "Buried Treasure Map 25": LOCATION_ID_BASE + 1500 + 25,
    "Buried Treasure Map 26": LOCATION_ID_BASE + 1500 + 26,
    "Buried Treasure Map 27": LOCATION_ID_BASE + 1500 + 27,
    "Buried Treasure Map 28": LOCATION_ID_BASE + 1500 + 28,
    "Buried Treasure Map 29": LOCATION_ID_BASE + 1500 + 29,
    "Buried Treasure Map 30": LOCATION_ID_BASE + 1500 + 30,
    "Buried Treasure Map 31": LOCATION_ID_BASE + 1500 + 31,
    "Buried Treasure Map 32": LOCATION_ID_BASE + 1500 + 32,
    "Buried Treasure Map 33": LOCATION_ID_BASE + 1500 + 33,
    "Buried Treasure Map 34": LOCATION_ID_BASE + 1500 + 34,
    "Buried Treasure Map 35": LOCATION_ID_BASE + 1500 + 35,
    "Buried Treasure Map 36": LOCATION_ID_BASE + 1500 + 36,
    "Buried Treasure Map 37": LOCATION_ID_BASE + 1500 + 37,
    "Buried Treasure Map 38": LOCATION_ID_BASE + 1500 + 38,
    "Buried Treasure Map 39": LOCATION_ID_BASE + 1500 + 39,
    "Buried Treasure Map 40": LOCATION_ID_BASE + 1500 + 40,
    "Buried Treasure Map 41": LOCATION_ID_BASE + 1500 + 41,
    "Buried Treasure Map 42": LOCATION_ID_BASE + 1500 + 42,
    "Buried Treasure Map 43": LOCATION_ID_BASE + 1500 + 43,
    "Buried Treasure Map 44": LOCATION_ID_BASE + 1500 + 44,
    "Buried Treasure Map 45": LOCATION_ID_BASE + 1500 + 45,
    "Buried Treasure Map 46": LOCATION_ID_BASE + 1500 + 46,
    "Buried Treasure Map 47": LOCATION_ID_BASE + 1500 + 47,
    "Buried Treasure Map 48": LOCATION_ID_BASE + 1500 + 48,
    "Buried Treasure Map 49": LOCATION_ID_BASE + 1500 + 49,
    "Buried Treasure Map 50": LOCATION_ID_BASE + 1500 + 50,
    "Buried Treasure Map 51": LOCATION_ID_BASE + 1500 + 51,
    "Buried Treasure Map 52": LOCATION_ID_BASE + 1500 + 52,
    "Buried Treasure Map 53": LOCATION_ID_BASE + 1500 + 53,
    "Buried Treasure Map 54": LOCATION_ID_BASE + 1500 + 54,
    "Buried Treasure Map 55": LOCATION_ID_BASE + 1500 + 55,
    "Buried Treasure Map 56": LOCATION_ID_BASE + 1500 + 56,
    "Buried Treasure Map 57": LOCATION_ID_BASE + 1500 + 57,
    "Buried Treasure Map 58": LOCATION_ID_BASE + 1500 + 58,
    "Buried Treasure Map 59": LOCATION_ID_BASE + 1500 + 59,
    "Buried Treasure Map 60": LOCATION_ID_BASE + 1500 + 60,
    "Buried Treasure Map 61": LOCATION_ID_BASE + 1500 + 61,
    "Buried Treasure Map 62": LOCATION_ID_BASE + 1500 + 62,
    "Buried Treasure Map 63": LOCATION_ID_BASE + 1500 + 63,
    "Buried Treasure Map 64": LOCATION_ID_BASE + 1500 + 64,
    "Buried Treasure Map 65": LOCATION_ID_BASE + 1500 + 65,
    "Buried Treasure Map 66": LOCATION_ID_BASE + 1500 + 66,
    "Buried Treasure Map 67": LOCATION_ID_BASE + 1500 + 67,
    "Buried Treasure Map 68": LOCATION_ID_BASE + 1500 + 68,
    "Buried Treasure Map 69": LOCATION_ID_BASE + 1500 + 69,
    "Buried Treasure Map 70": LOCATION_ID_BASE + 1500 + 70,
    "Buried Treasure Map 71": LOCATION_ID_BASE + 1500 + 71,
    "Buried Treasure Map 72": LOCATION_ID_BASE + 1500 + 72,
    "Buried Treasure Map 73": LOCATION_ID_BASE + 1500 + 73,
    "Buried Treasure Map 74": LOCATION_ID_BASE + 1500 + 74,
    "Buried Treasure Map 75": LOCATION_ID_BASE + 1500 + 75,
    "Buried Treasure Map 76": LOCATION_ID_BASE + 1500 + 76,
    "Buried Treasure Map 77": LOCATION_ID_BASE + 1500 + 77,
    "Buried Treasure Map 78": LOCATION_ID_BASE + 1500 + 78,
    "Buried Treasure Map 79": LOCATION_ID_BASE + 1500 + 79,
    "Buried Treasure Map 80": LOCATION_ID_BASE + 1500 + 80,
    "Buried Treasure Map 81": LOCATION_ID_BASE + 1500 + 81,
    "Buried Treasure Map 82": LOCATION_ID_BASE + 1500 + 82,
    "Buried Treasure Map 83": LOCATION_ID_BASE + 1500 + 83,
    "Buried Treasure Map 84": LOCATION_ID_BASE + 1500 + 84,
    "Buried Treasure Map 85": LOCATION_ID_BASE + 1500 + 85,
    "Buried Treasure Map 86": LOCATION_ID_BASE + 1500 + 86,
    "Buried Treasure Map 87": LOCATION_ID_BASE + 1500 + 87,
    "Buried Treasure Map 88": LOCATION_ID_BASE + 1500 + 88,
    "Buried Treasure Map 89": LOCATION_ID_BASE + 1500 + 89,
    "Buried Treasure Map 90": LOCATION_ID_BASE + 1500 + 90,
    "Buried Treasure Map 91": LOCATION_ID_BASE + 1500 + 91,
    "Buried Treasure Map 92": LOCATION_ID_BASE + 1500 + 92,
    "Buried Treasure Map 93": LOCATION_ID_BASE + 1500 + 93,
    "Buried Treasure Map 94": LOCATION_ID_BASE + 1500 + 94,
    "Buried Treasure Map 95": LOCATION_ID_BASE + 1500 + 95,
    "Buried Treasure Map 96": LOCATION_ID_BASE + 1500 + 96,
    "Buried Treasure Map 97": LOCATION_ID_BASE + 1500 + 97,
    "Buried Treasure Map 98": LOCATION_ID_BASE + 1500 + 98,
    "Buried Treasure Map 99": LOCATION_ID_BASE + 1500 + 99,
    "Buried Treasure Map 100": LOCATION_ID_BASE + 1500 + 100,
    "Day 1 Boss 1": LOCATION_ID_BASE + 1000 + 1,
    "Day 1 Boss 2": LOCATION_ID_BASE + 1000 + 2,
    "Day 1 Boss 3": LOCATION_ID_BASE + 1000 + 3,
    "Day 1 Boss 4": LOCATION_ID_BASE + 1000 + 4,
    "Day 1 Boss 5": LOCATION_ID_BASE + 1000 + 5,
    "Day 1 Boss 6": LOCATION_ID_BASE + 1000 + 6,
    "Day 1 Boss 7": LOCATION_ID_BASE + 1000 + 7,
    "Day 1 Boss 8": LOCATION_ID_BASE + 1000 + 8,
    "Day 1 Boss 9": LOCATION_ID_BASE + 1000 + 9,
    "Day 1 Boss 10": LOCATION_ID_BASE + 1000 + 10,
    "Day 1 Boss 11": LOCATION_ID_BASE + 1000 + 11,
    "Day 1 Boss 12": LOCATION_ID_BASE + 1000 + 12,
    "Day 1 Boss 13": LOCATION_ID_BASE + 1000 + 13,
    "Day 1 Boss 14": LOCATION_ID_BASE + 1000 + 14,
    "Day 1 Boss 15": LOCATION_ID_BASE + 1000 + 15,
    "Day 1 Boss 16": LOCATION_ID_BASE + 1000 + 16,
    "Day 1 Boss 17": LOCATION_ID_BASE + 1000 + 17,
    "Day 1 Boss 18": LOCATION_ID_BASE + 1000 + 18,
    "Day 1 Boss 19": LOCATION_ID_BASE + 1000 + 19,
    "Day 1 Boss 20": LOCATION_ID_BASE + 1000 + 20,
    "Day 1 Boss 21": LOCATION_ID_BASE + 1000 + 21,
    "Day 1 Boss 22": LOCATION_ID_BASE + 1000 + 22,
    "Day 1 Boss 23": LOCATION_ID_BASE + 1000 + 23,
    "Day 1 Boss 24": LOCATION_ID_BASE + 1000 + 24,
    "Day 1 Boss 25": LOCATION_ID_BASE + 1000 + 25,
    "Day 1 Boss 26": LOCATION_ID_BASE + 1000 + 26,
    "Day 1 Boss 27": LOCATION_ID_BASE + 1000 + 27,
    "Day 1 Boss 28": LOCATION_ID_BASE + 1000 + 28,
    "Day 1 Boss 29": LOCATION_ID_BASE + 1000 + 29,
    "Day 1 Boss 30": LOCATION_ID_BASE + 1000 + 30,
    "Day 2 Boss 1": LOCATION_ID_BASE + 1100 + 1,
    "Day 2 Boss 2": LOCATION_ID_BASE + 1100 + 2,
    "Day 2 Boss 3": LOCATION_ID_BASE + 1100 + 3,
    "Day 2 Boss 4": LOCATION_ID_BASE + 1100 + 4,
    "Day 2 Boss 5": LOCATION_ID_BASE + 1100 + 5,
    "Day 2 Boss 6": LOCATION_ID_BASE + 1100 + 6,
    "Day 2 Boss 7": LOCATION_ID_BASE + 1100 + 7,
    "Day 2 Boss 8": LOCATION_ID_BASE + 1100 + 8,
    "Day 2 Boss 9": LOCATION_ID_BASE + 1100 + 9,
    "Day 2 Boss 10": LOCATION_ID_BASE + 1100 + 10,
    "Day 2 Boss 11": LOCATION_ID_BASE + 1100 + 11,
    "Day 2 Boss 12": LOCATION_ID_BASE + 1100 + 12,
    "Day 2 Boss 13": LOCATION_ID_BASE + 1100 + 13,
    "Day 2 Boss 14": LOCATION_ID_BASE + 1100 + 14,
    "Day 2 Boss 15": LOCATION_ID_BASE + 1100 + 15,
    "Day 2 Boss 16": LOCATION_ID_BASE + 1100 + 16,
    "Day 2 Boss 17": LOCATION_ID_BASE + 1100 + 17,
    "Day 2 Boss 18": LOCATION_ID_BASE + 1100 + 18,
    "Day 2 Boss 19": LOCATION_ID_BASE + 1100 + 19,
    "Day 2 Boss 20": LOCATION_ID_BASE + 1100 + 20,
    "Day 2 Boss 21": LOCATION_ID_BASE + 1100 + 21,
    "Day 2 Boss 22": LOCATION_ID_BASE + 1100 + 22,
    "Day 2 Boss 23": LOCATION_ID_BASE + 1100 + 23,
    "Day 2 Boss 24": LOCATION_ID_BASE + 1100 + 24,
    "Day 2 Boss 25": LOCATION_ID_BASE + 1100 + 25,
    "Day 2 Boss 26": LOCATION_ID_BASE + 1100 + 26,
    "Day 2 Boss 27": LOCATION_ID_BASE + 1100 + 27,
    "Day 2 Boss 28": LOCATION_ID_BASE + 1100 + 28,
    "Day 2 Boss 29": LOCATION_ID_BASE + 1100 + 29,
    "Day 2 Boss 30": LOCATION_ID_BASE + 1100 + 30,
    "Shop - Delicate Burning Scene": LOCATION_ID_BASE + 600,
    "Shop - Delicate Drizzly Scene": LOCATION_ID_BASE + 601,
    "Shop - Delicate Luminous Scene 1": LOCATION_ID_BASE + 602,
    "Shop - Delicate Tranquil Scene": LOCATION_ID_BASE + 603,
    "Shop - Polished Burning Scene 1": LOCATION_ID_BASE + 604,
    "Shop - Delicate Luminous Scene 2": LOCATION_ID_BASE + 605,
    "Shop - Polished Tranquil Scene 1": LOCATION_ID_BASE + 606,
    "Shop - Polished Drizzly Scene 1": LOCATION_ID_BASE + 607,
    "Shop - Polished Burning Scene 2": LOCATION_ID_BASE + 608,
    "Shop - Polished Tranquil Scene 2": LOCATION_ID_BASE + 609,
    "Shop - Polished Tranquil Scene 3": LOCATION_ID_BASE + 610,
    "Shop - Polished Burning Scene 3": LOCATION_ID_BASE + 611,
    "Shop - Polished Burning Scene 4": LOCATION_ID_BASE + 612,
    "Shop - Polished Tranquil Scene 4": LOCATION_ID_BASE + 613,
    "Shop - Polished Luminous Scene 1": LOCATION_ID_BASE + 614,
    "Shop - Polished Luminous Scene 2": LOCATION_ID_BASE + 615,
    "Shop - Polished Drizzly Scene 2": LOCATION_ID_BASE + 616,
    "Shop - Polished Drizzly Scene 3": LOCATION_ID_BASE + 617,
    "Shop - Grand Burning Scene 1": LOCATION_ID_BASE + 618,
    "Shop - Grand Drizzly Scene 1": LOCATION_ID_BASE + 619,
    "Shop - Grand Tranquil Scene 1": LOCATION_ID_BASE + 620,
    "Shop - Grand Tranquil Scene 2": LOCATION_ID_BASE + 621,
    "Shop - Grand Luminous Scene": LOCATION_ID_BASE + 622,
    "Shop - Grand Drizzly Scene 2": LOCATION_ID_BASE + 623,
    "Shop - Grand Drizzly Scene 3": LOCATION_ID_BASE + 624,
    "Shop - Grand Burning Scene 2": LOCATION_ID_BASE + 625,
    "Shop - Grand Burning Scene 3": LOCATION_ID_BASE + 626,
    "Shop - Grand Tranquil Scene 3": LOCATION_ID_BASE + 627,
    "Shop - Besmirched Frame": LOCATION_ID_BASE + 628,
    "Shop - Wylder's Goblet": LOCATION_ID_BASE + 629,
    "Shop - Guardian's Goblet": LOCATION_ID_BASE + 630,
    "Shop - Ironeye's Goblet": LOCATION_ID_BASE + 631,
    "Shop - Duchess' Goblet": LOCATION_ID_BASE + 632,
    "Shop - Raider's Goblet": LOCATION_ID_BASE + 633,
    "Shop - Revenant's Goblet": LOCATION_ID_BASE + 634,
    "Shop - Recluse's Goblet": LOCATION_ID_BASE + 635,
    "Shop - Executor's Goblet": LOCATION_ID_BASE + 636,
    "Shop - Sacred Erdtree Grail": LOCATION_ID_BASE + 637,
    "Shop - Spirit Shelter Grail": LOCATION_ID_BASE + 638,
    "Shop - Giant's Cradle Grail": LOCATION_ID_BASE + 639,
    "Shop - Polite Bow": LOCATION_ID_BASE + 640,
    "Shop - Strength": LOCATION_ID_BASE + 641,
    "Shop - Warm Welcome": LOCATION_ID_BASE + 642,
    "Shop - Fancy Spin": LOCATION_ID_BASE + 643,
    "Shop - Crossed Legs": LOCATION_ID_BASE + 644,
    "Shop - Rest": LOCATION_ID_BASE + 645,
    "Shop - Sitting Sideways": LOCATION_ID_BASE + 646,
    "Shop - Fire Spur Me": LOCATION_ID_BASE + 647,
    "Shop - As You Wish": LOCATION_ID_BASE + 648,
    "Shop - Heartening Cry": LOCATION_ID_BASE + 649,
    "Shop - Calm Down": LOCATION_ID_BASE + 650,
    "Shop - Finger Snap": LOCATION_ID_BASE + 651,
    "Shop - Prayer": LOCATION_ID_BASE + 652,
    "Shop - Rapture": LOCATION_ID_BASE + 653,
    "Shop - Erudition": LOCATION_ID_BASE + 654,
    "Shop - Outer Order": LOCATION_ID_BASE + 655,
    "Shop - Curtsy": LOCATION_ID_BASE + 656,
    "Shop - Reverential Bow": LOCATION_ID_BASE + 657,
    "Shop - Dejection": LOCATION_ID_BASE + 658,
    "Shop - Extreme Repentance": LOCATION_ID_BASE + 659,
    "Shop - Patches' Crouch": LOCATION_ID_BASE + 660,
    "Shop - Dozing Cross-Legged": LOCATION_ID_BASE + 661,
    "Shop - Desperate Prayer": LOCATION_ID_BASE + 662,
    "Shop - Hoslow's Oath": LOCATION_ID_BASE + 663,
    "Shop - Inner Order": LOCATION_ID_BASE + 664,
    "Shop - What Do You Want?": LOCATION_ID_BASE + 665,
    "Shop - My Lord": LOCATION_ID_BASE + 666,
    "Shop - Grovel For Mercy": LOCATION_ID_BASE + 667,
    "Shop - Spread Out": LOCATION_ID_BASE + 668,
    "Shop - Balled Up": LOCATION_ID_BASE + 669,
    "Shop - Golden Order Totality": LOCATION_ID_BASE + 670,
    "Shop - Prattling Pate Hello": LOCATION_ID_BASE + 671,
    "Shop - Prattling Pate Thank you": LOCATION_ID_BASE + 672,
    "Shop - Prattling Pate Wonderful": LOCATION_ID_BASE + 673,
    "Shop - Prattling Pate Please help": LOCATION_ID_BASE + 674,
    "Shop - Prattling Pate My beloved": LOCATION_ID_BASE + 675,
    "Shop - Prattling Pate Apologies": LOCATION_ID_BASE + 676,
    "Shop - Prattling Pate Let's get to it": LOCATION_ID_BASE + 677,
    "Shop - Prattling Pate You're beautiful": LOCATION_ID_BASE + 678,
    "Shop - Scholar's Goblet": LOCATION_ID_BASE + 679,
    "Shop - Undertaker's Goblet": LOCATION_ID_BASE + 680,
    "Shop - Scadutree Grail": LOCATION_ID_BASE + 681,
    "Shop - Grand Burning Scene 4": LOCATION_ID_BASE + 682,
    "Shop - Grand Tranquil Scene 4": LOCATION_ID_BASE + 683,
    "Garb - Wylder Abysswalker": LOCATION_ID_BASE + 900,
    "Garb - Wylder Lion Knight": LOCATION_ID_BASE + 901,
    "Garb - Wylder Dawn": LOCATION_ID_BASE + 902,
    "Garb - Wylder Darkness": LOCATION_ID_BASE + 903,
    "Garb - Guardian Sunlight Knight": LOCATION_ID_BASE + 904,
    "Garb - Guardian Wayfarer": LOCATION_ID_BASE + 905,
    "Garb - Guardian Dawn": LOCATION_ID_BASE + 906,
    "Garb - Guardian Darkness": LOCATION_ID_BASE + 907,
    "Garb - Ironeye Ringfinger": LOCATION_ID_BASE + 908,
    "Garb - Ironeye Sellsword": LOCATION_ID_BASE + 909,
    "Garb - Ironeye Dawn": LOCATION_ID_BASE + 910,
    "Garb - Ironeye Darkness": LOCATION_ID_BASE + 911,
    "Garb - Duchess Black Leather": LOCATION_ID_BASE + 912,
    "Garb - Duchess Wraith": LOCATION_ID_BASE + 913,
    "Garb - Duchess Dawn": LOCATION_ID_BASE + 914,
    "Garb - Duchess Darkness": LOCATION_ID_BASE + 915,
    "Garb - Raider Rock-like": LOCATION_ID_BASE + 916,
    "Garb - Raider Catarina": LOCATION_ID_BASE + 917,
    "Garb - Raider Dawn": LOCATION_ID_BASE + 918,
    "Garb - Raider Darkness": LOCATION_ID_BASE + 919,
    "Garb - Revenant The Sister in the Painting": LOCATION_ID_BASE + 920,
    "Garb - Revenant Dragon School": LOCATION_ID_BASE + 921,
    "Garb - Revenant Dawn": LOCATION_ID_BASE + 922,
    "Garb - Revenant Darkness": LOCATION_ID_BASE + 923,
    "Garb - Recluse Heretic Sorcerer": LOCATION_ID_BASE + 924,
    "Garb - Recluse Emerald Fate": LOCATION_ID_BASE + 925,
    "Garb - Recluse Dawn": LOCATION_ID_BASE + 926,
    "Garb - Recluse Darkness": LOCATION_ID_BASE + 927,
    "Garb - Executor Thorns": LOCATION_ID_BASE + 928,
    "Garb - Executor Sable Church": LOCATION_ID_BASE + 929,
    "Garb - Executor Dawn": LOCATION_ID_BASE + 930,
    "Garb - Executor Darkness": LOCATION_ID_BASE + 931,
    "Garb - Scholar Dawn": LOCATION_ID_BASE + 932,
    "Garb - Scholar Darkness": LOCATION_ID_BASE + 933,
    "Garb - Scholar Pardoner": LOCATION_ID_BASE + 934,
    "Garb - Scholar Xanthous": LOCATION_ID_BASE + 935,
    "Garb - Undertaker Dawn": LOCATION_ID_BASE + 936,
    "Garb - Undertaker Darkness": LOCATION_ID_BASE + 937,
    "Garb - Undertaker Brass": LOCATION_ID_BASE + 938,
    "Garb - Undertaker Lord's Blade": LOCATION_ID_BASE + 939,
    "Murk 1": LOCATION_ID_BASE + 700,
    "Murk 2": LOCATION_ID_BASE + 701,
    "Murk 3": LOCATION_ID_BASE + 702,
    "Murk 4": LOCATION_ID_BASE + 703,
    "Murk 5": LOCATION_ID_BASE + 704,
    "Murk 6": LOCATION_ID_BASE + 705,
    "Murk 7": LOCATION_ID_BASE + 706,
    "Murk 8": LOCATION_ID_BASE + 707,
    "Murk 9": LOCATION_ID_BASE + 708,
    "Murk 10": LOCATION_ID_BASE + 709,
    "Murk 11": LOCATION_ID_BASE + 710,
    "Murk 12": LOCATION_ID_BASE + 711,
    "Murk 13": LOCATION_ID_BASE + 712,
    "Murk 14": LOCATION_ID_BASE + 713,
    "Murk 15": LOCATION_ID_BASE + 714,
    "Murk 16": LOCATION_ID_BASE + 715,
    "Murk 17": LOCATION_ID_BASE + 716,
    "Murk 18": LOCATION_ID_BASE + 717,
    "Murk 19": LOCATION_ID_BASE + 718,
    "Murk 20": LOCATION_ID_BASE + 719,
    "Murk 21": LOCATION_ID_BASE + 720,
    "Murk 22": LOCATION_ID_BASE + 721,
    "Murk 23": LOCATION_ID_BASE + 722,
    "Murk 24": LOCATION_ID_BASE + 723,
    "Murk 25": LOCATION_ID_BASE + 724,
    "Murk 26": LOCATION_ID_BASE + 725,
    "Murk 27": LOCATION_ID_BASE + 726,
    "Bosses Killed (1)": LOCATION_ID_BASE + 801,
    "Bosses Killed (3)": LOCATION_ID_BASE + 803,
    "Bosses Killed (5)": LOCATION_ID_BASE + 805,
    "Bosses Killed (10)": LOCATION_ID_BASE + 810,
    "Bosses Killed (20)": LOCATION_ID_BASE + 820,
    "Nightfarer Reserve": LOCATION_ID_BASE + 600,
}

SHOP_LOCATIONS = [
    "Shop - Delicate Burning Scene",
    "Shop - Delicate Drizzly Scene",
    "Shop - Delicate Luminous Scene 1",
    "Shop - Delicate Tranquil Scene",
    "Shop - Polished Burning Scene 1",
    "Shop - Delicate Luminous Scene 2",
    "Shop - Polished Tranquil Scene 1",
    "Shop - Polished Drizzly Scene 1",
    "Shop - Polished Burning Scene 2",
    "Shop - Polished Tranquil Scene 2",
    "Shop - Polished Tranquil Scene 3",
    "Shop - Polished Burning Scene 3",
    "Shop - Polished Burning Scene 4",
    "Shop - Polished Tranquil Scene 4",
    "Shop - Polished Luminous Scene 1",
    "Shop - Polished Luminous Scene 2",
    "Shop - Polished Drizzly Scene 2",
    "Shop - Polished Drizzly Scene 3",
    "Shop - Grand Burning Scene 1",
    "Shop - Grand Drizzly Scene 1",
    "Shop - Grand Tranquil Scene 1",
    "Shop - Grand Tranquil Scene 2",
    "Shop - Grand Luminous Scene",
    "Shop - Grand Drizzly Scene 2",
    "Shop - Grand Drizzly Scene 3",
    "Shop - Grand Burning Scene 2",
    "Shop - Grand Burning Scene 3",
    "Shop - Grand Tranquil Scene 3",
    "Shop - Besmirched Frame",
    "Shop - Wylder's Goblet",
    "Shop - Guardian's Goblet",
    "Shop - Ironeye's Goblet",
    "Shop - Duchess' Goblet",
    "Shop - Raider's Goblet",
    "Shop - Revenant's Goblet",
    "Shop - Recluse's Goblet",
    "Shop - Executor's Goblet",
    "Shop - Sacred Erdtree Grail",
    "Shop - Spirit Shelter Grail",
    "Shop - Giant's Cradle Grail",
    "Shop - Polite Bow",
    "Shop - Strength",
    "Shop - Warm Welcome",
    "Shop - Fancy Spin",
    "Shop - Crossed Legs",
    "Shop - Rest",
    "Shop - Sitting Sideways",
    "Shop - Fire Spur Me",
    "Shop - As You Wish",
    "Shop - Heartening Cry",
    "Shop - Calm Down",
    "Shop - Finger Snap",
    "Shop - Prayer",
    "Shop - Rapture",
    "Shop - Erudition",
    "Shop - Outer Order",
    "Shop - Curtsy",
    "Shop - Reverential Bow",
    "Shop - Dejection",
    "Shop - Extreme Repentance",
    "Shop - Patches' Crouch",
    "Shop - Dozing Cross-Legged",
    "Shop - Desperate Prayer",
    "Shop - Hoslow's Oath",
    "Shop - Inner Order",
    "Shop - What Do You Want?",
    "Shop - My Lord",
    "Shop - Grovel For Mercy",
    "Shop - Spread Out",
    "Shop - Balled Up",
    "Shop - Golden Order Totality",
    "Shop - Prattling Pate Hello",
    "Shop - Prattling Pate Thank you",
    "Shop - Prattling Pate Wonderful",
    "Shop - Prattling Pate Please help",
    "Shop - Prattling Pate My beloved",
    "Shop - Prattling Pate Apologies",
    "Shop - Prattling Pate Let's get to it",
    "Shop - Prattling Pate You're beautiful",
    "Shop - Scholar's Goblet",
    "Shop - Undertaker's Goblet",
    "Shop - Scadutree Grail",
    "Shop - Grand Burning Scene 4",
    "Shop - Grand Tranquil Scene 4",
    "Garb - Wylder Abysswalker",
    "Garb - Wylder Lion Knight",
    "Garb - Wylder Dawn",
    "Garb - Wylder Darkness",
    "Garb - Guardian Sunlight Knight",
    "Garb - Guardian Wayfarer",
    "Garb - Guardian Dawn",
    "Garb - Guardian Darkness",
    "Garb - Ironeye Ringfinger",
    "Garb - Ironeye Sellsword",
    "Garb - Ironeye Dawn",
    "Garb - Ironeye Darkness",
    "Garb - Duchess Black Leather",
    "Garb - Duchess Wraith",
    "Garb - Duchess Dawn",
    "Garb - Duchess Darkness",
    "Garb - Raider Rock-like",
    "Garb - Raider Catarina",
    "Garb - Raider Dawn",
    "Garb - Raider Darkness",
    "Garb - Revenant The Sister in the Painting",
    "Garb - Revenant Dragon School",
    "Garb - Revenant Dawn",
    "Garb - Revenant Darkness",
    "Garb - Recluse Heretic Sorcerer",
    "Garb - Recluse Emerald Fate",
    "Garb - Recluse Dawn",
    "Garb - Recluse Darkness",
    "Garb - Executor Thorns",
    "Garb - Executor Sable Church",
    "Garb - Executor Dawn",
    "Garb - Executor Darkness",
    "Garb - Scholar Dawn",
    "Garb - Scholar Darkness",
    "Garb - Scholar Pardoner",
    "Garb - Scholar Xanthous",
    "Garb - Undertaker Dawn",
    "Garb - Undertaker Darkness",
    "Garb - Undertaker Brass",
    "Garb - Undertaker Lord's Blade",
]

# Defeat location, expedition unlock item required to reach it.
BASE_NIGHTLORDS: List[Tuple[str, str]] = [
    ("Nightlord - Gladius", "Expedition Unlock - Tricephalos"),
    ("Nightlord - Adel", "Expedition Unlock - Adel"),
    ("Nightlord - Gnoster", "Expedition Unlock - Gnoster"),
    ("Nightlord - Maris", "Expedition Unlock - Maris"),
    ("Nightlord - Libra", "Expedition Unlock - Libra"),
    ("Nightlord - Fulghor", "Expedition Unlock - Fulghor"),
    ("Nightlord - Caligo", "Expedition Unlock - Caligo"),
]

DLC_NIGHTLORDS: List[Tuple[str, str]] = [
    ("Nightlord - Harmonia", "Expedition Unlock - Harmonia"),
    ("Nightlord - Straghess", "Expedition Unlock - Straghess"),
]

# Defeat location, Everdark unlock item. These do not count toward the Heolstor gate.
EVERDARK_NIGHTLORDS: List[Tuple[str, str]] = [
    ("Everdark - Gladius", "Everdark Unlock - Gladius"),
    ("Everdark - Adel", "Everdark Unlock - Adel"),
    ("Everdark - Gnoster", "Everdark Unlock - Gnoster"),
    ("Everdark - Maris", "Everdark Unlock - Maris"),
    ("Everdark - Libra", "Everdark Unlock - Libra"),
    ("Everdark - Fulghor", "Everdark Unlock - Fulghor"),
    ("Everdark - Caligo", "Everdark Unlock - Caligo"),
]

EVERDARK_DLC: List[Tuple[str, str]] = [
    ("Everdark - Harmonia", "Everdark Unlock - Harmonia"),
]

SPECIFIC_LOCATION = {
    "gladius": "Nightlord - Gladius",
    "adel": "Nightlord - Adel",
    "gnoster": "Nightlord - Gnoster",
    "maris": "Nightlord - Maris",
    "libra": "Nightlord - Libra",
    "fulghor": "Nightlord - Fulghor",
    "caligo": "Nightlord - Caligo",
    "heolstor": "Nightlord - Heolstor",
    "harmonia": "Nightlord - Harmonia",
    "straghess": "Nightlord - Straghess",
}
